### ISSUE TITLE
[rup_table] Problema PK múltiple anidada. (v2.4.2)

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#1]
Hemos encontrado un problema al utilizar una PK múltiple que sea “anidada”. Lo que nos ocurre es que tanto el id de la fila como la columna que después utiliza para enviar la pk (“pkCol”) las calcula mal. Intenta acceder al objeto como si no estaría anidado, con lo que no funciona, y el resultado es “undefined~undefined”.

**Ejem:** 
```javascript
primaryKey: ["vivienda.numVivienda","propietario.numPropietario"],
```
Creo que esto tiene una solución “sencilla” aunque no he probado todas las posibles implicaciones. 

**Fichero:** rup.table.core-2.4.2.js
**Líneas:** 249 y 312

**Actual:**
```javascript
249: retValue+=rowObject[settings.primaryKey[i]]+settings.multiplePkToken;
312: retValue+=elem[settings.primaryKey[i]]+settings.multiplePkToken;
```
**Corrección:**
```javascript
249: retValue+=$.rup_utils.unnestjson(rowObject)[settings.primaryKey[i]]+settings.multiplePkToken;
312: retValue+=$.rup_utils.unnestjson(elem)[settings.primaryKey[i]]+settings.multiplePkToken;
```
Aunque estamos utilizando la versión 2.4.2 en la versión 2.4.5 parece que no está cambiado.

**Comment by udaejie** [comment]
La solución ha sido probada y se considera correcta.

Se incluirá en la siguiente versión -v.2.4.6- de UDA.
