### ISSUE TITLE
[rup_table.formEdit] Evento jqGridAddEditAfterFillData. (v2.4.6) 

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#10]
Al capturar el evento **jqGridAddEditAfterFillData**, la primera vez, no viene informada la operación ("add"/"edit").

El caso es que estamos intentando realizar alguna acción (en este caso limpiar unos campo) al utilizar el botón clonar del componente. Y dado que el evento _jqGridAddEditAfterShowForm_ se ejecuta antes de rellenar los datos en este caso, hemos optado por usar el otro evento. Aunque en el caso del clonar este evento se lanza 2 veces, una cuando limpia el formulario. como si fuera un Add, y otra una vez se cargan los datos clonados.

Por lo que he estado viendo el problema esta en la función _editGridRow_, que se extiende en el fichero _rup.table.formEdit-2.4.6.js_, que al invocar a la función $.jgrid.fillData no se le esta pasando el tipo de operación para que pueda propagarlo a los futuros eventos. Aunque solo pasa la primera vez que se lanza el evento, después la variable parece que la toma como global y se actualiza, aunque se sigue sin enviar explicitamente. 

**Fichero:** rup.table.formEdit-2.4.6.js
**Funcion:** editGridRow
**Líneas:** 1593

**Actual:**
```javascript
$.proxy($.jgrid.fillData, $t)(rowid, $t);
```

**Propuesta:**
```javascript
$.proxy($.jgrid.fillData, $t)(rowid, $t, undefined, frmoper); 
```

Por otro lado la funcion _cloneElement_ del mismo fichero, también hace una llamada a jgrid.fillData sin especificar operación, estaría bien informarle una, ya sea "add" o una nueva "clone".

**Fichero:** rup.table.formEdit-2.4.6.js
**Funcion:** cloneElement
**Líneas:** 737

**Actual:**
```javascript
jQuery.proxy(jQuery.jgrid.fillData, $self[0])(selectedRow, $self[0]);
```

**Propuesta1:**
```javascript
jQuery.proxy(jQuery.jgrid.fillData, $self[0])(selectedRow, $self[0], undefined, "add");
```

**Propuesta2:**
```javascript
jQuery.proxy(jQuery.jgrid.fillData, $self[0])(selectedRow, $self[0], undefined, "clone");
```
Sinceramente no he mirado para que sirve el 3 parámetro pero dado que ahora no se esta enviando y no hay un error conocido, lo propongo como undefined, aunque quizás habría que informarlo.

**Posible Mejora**
En relación al error anterior, estaría bien tener la posibilidad de saber si la operación ejecutada en un "clone" al igual que podemos saber cuando es un "add" o un "edit", para poder actuar de forma especial en ese caso si fuera necesario.

**Comment by enekoza** [comment]
Se ha añadido un nuevo valor para la propiedad fmoper y de este modo identificar la operación de clonado. El nuevo tipo de operación se identifica mediante el valor "clone".

Junto con esta modificación se ha mejorado la gestión para que el evento jqGridAddEditAfterShowForm se lance una única vez en la ejecución de la operación del clonado.
