### ISSUE TITLE
[rup_dialog-AJAX] Fallo al asignar un error propio en dialogo tipo Ajax (v3.3.0) 

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#100]
Estamos teniendo problemas con los rup_dialog del tipo Ajax al intentar poner un error propio cuando esa llamada ajax falla:
```
type: $.rup.dialog.AJAX,
ajaxOptions: {
	error: function (data, textStatus, XMLHttpRequest){
		console.log("error");
	}
},
```
Nos esta pasando que antes de invocar a nuestro método de error el código del rup_dialog esta fallando:

![image](https://user-images.githubusercontent.com/11626735/37596360-37253f1e-2b7c-11e8-9da5-b5dfc91e77ee.png)
Esta intentando abrir un mensaje de error con una función que parece que no existe.
```
$(document).rup().msgAlert({
     message: $.rup.i18nParse($.rup.i18n.base, 'rup_dialog.errorLoadingData')
});
```

Creemos que lo mejor seria quitar este mensaje o solo ponerlo en el caso de no tener una función de error propia, dado que, si se soluciona el error y se deja el mensaje, imposibilita tener una gestión de errores propia y menos intrusiva que un mensaje de alerta genérico:
```
ajaxOptions.error = function (XMLHttpRequest, textStatus, errorThrown) { //en caso de error mostramos un mensaje de alerta
    $.unblockUI();
    if (settings.ajaxOptions && settings.ajaxOptions.error !== undefined && settings.ajaxOptions.error !== null && typeof settings.ajaxOptions.error === 'function') {
        settings.ajaxOptions.error(XMLHttpRequest, textStatus, errorThrown);
    } else {
        // Alerta solo si no hay error propio
        $.rup_messages("msgAlert",{
            message: $.rup.i18nParse($.rup.i18n.base, 'rup_dialog.errorLoadingData')
        });
    }
};
```

**Comment by xaabi6** [comment]
El commit f114415176d9ad0fd8cd7643aff99a0f4829ba8c corrigió esta issue.
