### ISSUE TITLE
[rup_validate] Cambio de comportamiento con versión 3.3.0

### ISSUE THREAD

**Issue by Menengol** [UDA-EJIE/udaRUP#102]
Hola,

Hemos actualizado de la versión 3.2.0 a la 3.3.0 y nos ha solucionado varios problemas que teníamos.

Sin embargo, hemos visto que algún detalle de las validaciones ha cambiado.
Ya no muestra la etiqueta del elemento si no directamente el atributo name del mismo.

Gracias y un saludo

**Comment by xaabi6** [comment]
Hola @Menengol, esos cambios de los que hablas fueron intencionados.

Dicho esto, aprovecho para comentarte que en el commit 62731f0 se añadió el soporte para coger el texto del label.

Un saludo
