### ISSUE TITLE
Al usar plugin inlineedit en rup_table, no crea botones extra en toolbar

### ISSUE THREAD

**Issue by bilopavi** [UDA-EJIE/udaRUP#105]
Hola,

Al usar usar el plugin inlineedit en rup_table, no crea botones extra en el toolbar definidos en 
```
core:{ 
	operations: operaciones
}
```

Hay una diferencia entre la gestión del toolbar en formedit vs inlineedit

**inlineedit**--> preConfigureInlineEdit--> **machaca core.operations** con sus botones por defecto

[rup.table.inlineEdit.js línea 170](https://github.com/UDA-EJIE/udaRUP/blob/master/src/rup_table/rup.table.inlineEdit.js#L170) 

```
settings.core.operations = {
				'add': {
					name: $.rup.i18nParse($.rup.i18n.base,'rup_table.new'),
					icon: self._ADAPTER.CONST.core.operations.defaultOperations.add.icon,
					enabled: function(){
......................
.......................
.......................

```
mientras que en

**formedit** -->preConfigureFormEdit --> **extiende core.operations**, con los botones por defecto para el plugin formedit

[rup.table.formEdit.js línea 145](https://github.com/UDA-EJIE/udaRUP/blob/master/src/rup_table/rup.table.formEdit.js#L145)

```
settings.core.defaultOperations = {
				'add': {
					name: $.rup.i18nParse($.rup.i18n.base, 'rup_table.new'),
					icon: self._ADAPTER.CONST.core.operations.defaultOperations.add.icon,
					enabled: function 
.......................
.......................
.......................
```
[rup.table.formEdit.js línea 207](https://github.com/UDA-EJIE/udaRUP/blob/master/src/rup_table/rup.table.formEdit.js#L207)
`$.extend(true, settings.core.operations, settings.core.defaultOperations);`

Lo que hace que se mantengan los botones que hemos añadido

Un saludo

**Comment by xaabi6** [comment]
Aupa @bilopavi 

El problema ha sido corregido y estará disponible en la próxima versión que liberemos. El siguiente commit es el que aplica los cambios para la corrección: https://github.com/UDA-EJIE/udaRUP/commit/a8c1cdca95010088b78fafc39e9b0d7f5a005420
