### ISSUE TITLE
Autocomplete solapado por Ventana Modal

### ISSUE THREAD

**Issue by Jozenrike** [UDA-EJIE/udaRUP#106]
cuando tienes un autocomplete en una ventana modal, ya sea edicion o creacion(supongo que en clonar tambien), los datos cargados se muestran por detras de la ventana y no se pueden seleccionar con el raton.

**Comment by bilopavi** [comment]
hola,

Yo he tenido ese mismo problema :) se resuelve usando la propiedad del autocomplete: 

- **menuAppendTo** : _Permite especificar mediante un selector de jQuery el elemento del DOM al que se añadirá el menú desplegable._

`menuAppendTo:$("#idAutocomplete").parent()`

Espero que te sirva

Un saludo

**Comment by Jozenrike** [comment]
ya, si he usado esa solucion pero da problemas de solapamiento con otros dialogos
ademas hay algunas cosillas que quedan raras en estilo del desplegable, pero fundamentalmente que el desplegable se queda como encerrado en la ventana

![image](https://user-images.githubusercontent.com/12089550/39865207-6701a99a-544c-11e8-8202-fc37e0318880.png)

es el mismo combo, con los combos normales al menos no pasa, y con los autocompletes solo puedo verlo con el menuAppendTo. Yo entiendo que esta relacionado.

Aun asi, gracias.
