### ISSUE TITLE
funcion Change autocomplete

### ISSUE THREAD

**Issue by Jozenrike** [UDA-EJIE/udaRUP#107]
cuando entras en la funcion change de un autocomplete, unicamente se cambia el campo del label y no el del value.
Por lo que si mi combo tiene como valores:
·Label: "lA"
·Value: "vA"
y cambio a los valores:
·Label: "lB"
·Value: "vB"
En el Change entraria como:
·Label: "lB"
·Value: "vA"
y no sería hasta salir de la funcion, cuando los valores estarían correctos de nuevo

Además, al borrar el campo el label se limpia pero el value se queda sin limpiar

**Comment by hmartinez85** [comment]
Buenos días,

He probado  y dentro del change del rup, si lo está cambiando, además al borrar el campo el val también me lo esta cambiando, puedes indicarme algún dato más y la versión en la que lo haces.

Gracias.

**Comment by GardiHuts** [comment]
Buenas,
nosotros estamos con la versión 3.4.0 y lo que nos pasa con el change es que se lanza 2 veces al modificar el contenido del autocomplete, la primera vez con el valor anterior y la segunda vez con el valor nuevo.

Poniendo un console.log en el change que pinte el valor entre # tenemos el siguiente resultado al seleccionar una opción teniendo el autocomplete vacío:
![image](https://user-images.githubusercontent.com/11626735/41655171-4722a51a-748c-11e8-9ada-8b2288c36094.png)
Y si una vez esta seleccionado, cambiamos el valor, se vuelve a lanzar 2 veces con el valor anterior y el nuevo:
![image](https://user-images.githubusercontent.com/11626735/41655474-44442a3e-748d-11e8-8e67-5b14bee8eae8.png)
Si en cambio borramos el contenido se lanza una única vez pero con el valor antiguo:
![image](https://user-images.githubusercontent.com/11626735/41655509-627f21e8-748d-11e8-9e9c-871ee1751b56.png)

La definición del autocomplete que tenemos para el ejemplo es la siguiente:
```
	$("#selector").rup_autocomplete({
		source: $.rup.CTX_PATH + "url",
		sourceParam: {label:"label", value:"value"},
		change: function(event){
			console.log("Change: #"+$("#selector").rup_autocomplete("getRupValue")+"#");
		}
	});
```

No se si igual la incidencia de @Jozenrike se habrá solucionado en esta nueva versión por que tampoco la puedo reproducir, pero el change sigue dando algún problema.

**Comment by Jozenrike** [comment]
mi caso es el siguiente
v3.3 y v3.4, en ambas fallaba
Importante, sucede al **utilizar las flechas** para seleccionar. 
Uso las flechas porque tengo otro poblema abierto con los combos, con el menuappendto que se solapa con otros dialogos si lo intento usar para que el desplegable del combo no se quede por detras de la ventana modal de detalle. Como vi que se liaba todo mucho preferi comentarlo aqui.

unos cuantos recortes:

· Primera seleccion en mi combo:
![image](https://user-images.githubusercontent.com/12089550/41657533-f8010f00-7493-11e8-977d-f7911be44a3d.png)
· Segunda Seleccion(el valor que sale, es el id del anterior label, y asi uno tras otro, el valor siempre lleva uno de retraso):
![image](https://user-images.githubusercontent.com/12089550/41657558-0bcc9d06-7494-11e8-80bf-2642f45297da.png)
·tercera seleccion del mismo combo:
El id es del anterior, el del órgano colegiado, pero el label es el que yo he seleccionado, y se empiezan a mostrar mal los labels
![image](https://user-images.githubusercontent.com/12089550/41657810-d7e731f8-7494-11e8-8541-38edf18c5d8f.png)

· Si borro el campo del combo:
Se queda el valor por detras pero el label va bien
![image](https://user-images.githubusercontent.com/12089550/41657911-27f0e842-7495-11e8-9619-a6e0e3ee4b9a.png)

codigo del combo:
![image](https://user-images.githubusercontent.com/12089550/41658208-f921706c-7495-11e8-851f-6d91229f23a7.png)
