### ISSUE TITLE
navegacion entre detalles UDA 3.4

### ISSUE THREAD

**Issue by Jozenrike** [UDA-EJIE/udaRUP#108]
en uda 3.4 la navegacion entre detalles ha dejado de funcionar, en la 3.3 funcionaba sin problemas

![image](https://user-images.githubusercontent.com/12089550/39992374-d7f2799e-5772-11e8-80a5-5a7cedb60da9.png)

**Comment by xaabi6** [comment]
Hola @Jozenrike , ¿podrías decirnos el nombre del componente afectado?

Gracias y un saludo

**Comment by Jozenrike** [comment]
@xaabi6 Los dialogos, su navegación concretamente

**Comment by xaabi6** [comment]
¿Podrías darme indicaciones para reproducir el fallo @Jozenrike ?

**Comment by xaabi6** [comment]
Hola @Jozenrike , prueba por favor en los siguientes componentes a ver si puedes reproducir el fallo que comentas, ya que a nosotros nos funciona perfectamente.

- http://desarrollo.jakina.ejiedes.net:7001/x21aAppWar/table/formEdit

- http://desarrollo.jakina.ejiedes.net:7001/x21aAppWar/table/formEditMultiselection

**Comment by Menengol** [comment]
Hola,

La diferencia entre nuestra aplicación y la vuestra es que nosotros usamos en ese componente la compatibilidad con jQueryUI.

Parece que al usar el adaptador "table_jqueryui" no hace alguna cosa o la hace de forma diferente.

Gracias y un saludo
