### ISSUE TITLE
Añadir en edición en línea con multiselección

### ISSUE THREAD

**Issue by bilopavi** [UDA-EJIE/udaRUP#109]
Hola,
Hemos tenido el caso de una tabla con edición en línea y multiselección
El botón añadir, no genera una línea nueva, porque se ejecuta
https://github.com/UDA-EJIE/udaRUP/blob/master/src/rup_table/rup.table.inlineEdit.js#L790
```javascript
if ($self.triggerHandler('rupTable_beforeAddRow', [auxOptions])!==false){
	$self.jqGrid('addRow', $.extend({},auxOptions));
}
```

y en consecuencia ejecuta 
https://github.com/UDA-EJIE/udaRUP/blob/master/src/rup_table/rup.table.multiselection.js#L850
```javascript
'rupTable_beforeAddRow.multiselection': function (event, addCloneOptions) {$self._checkSelectedElements(function () {
		$self.jqGrid('editGridRow', 'new', addCloneOptions);
		$self.rup_table('resetSelection');
		$self.rup_table('clearHighlightedEditableRows');
	});
	return false;}
```
Lo que provoca que no se ejecute la función addRow

Lo hemos corregido de esta manera
```javascript
 $self.on('rupTable_beforeAddRow.multiselection', function(event,
		addCloneOptions) {
	//si edición en línea no comprobamos elementos seleccionados y devolvemos true
	if ($self[0].p.inlineEdit) {
		return true;
	}
	$self._checkSelectedElements(function() {
		$self.jqGrid('editGridRow', 'new', addCloneOptions);
		$self.rup_table('resetSelection');
		$self.rup_table('clearHighlightedEditableRows');
	});
	return false;
});
```

Luego al intentar añadir validaciones, nos hemos encontrado con que las validaciones RUP, no se están gestionando correctamente, ya que el nombre de la columna sale en el mensaje de error y el name de la columna como Etiqueta del error (adjunto imagen)
![validacionformedit](https://user-images.githubusercontent.com/15363919/40057716-55ad0994-584f-11e8-811d-880bea5d3075.JPG)
En cambio, si la validación se define en el colModel, los textos son correctos, pero la apariencia es distinta a la habitual, porque el error se muestra en una ventana modal y con color azul
![validacioncolmodel](https://user-images.githubusercontent.com/15363919/40057768-8223582a-584f-11e8-917f-7b7dd1e55137.JPG)

Esto no lo hemos corregido

Un saludo

Víctor

**Comment by xaabi6** [comment]
Aupa @bilopavi, sobre lo que comentas de las validaciones, nosotros no sufrimos ese fallo, no obstante, se ha añadido soporte para que preferentemente use los labels (en caso de estar disponibles y correctamente enlazados) en el siguiente commit: 62731f0
