### ISSUE TITLE
(v3.4.0) Issue #98 sobrescribe la solución para la Issue #91

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#110]
Hemos visto que la solución aplicada para solucionar la Issue #98 ha sobrescrito el cambio realizado para solucionar la Issue #91.  Con lo que la #91 no esta solucionada en la 3.4.0.

**Comment by xaabi6** [comment]
Hola @GardiHuts, la issue #98 revertió el cambio de la #91 por accidente. De todos modos, esta última ha vuelto a quedar corregida con los cambios aplicados en el commit 2c2ee63
