### ISSUE TITLE
funcion select autocomplete 

### ISSUE THREAD

**Issue by jortizza** [UDA-EJIE/udaRUP#111]
En un autocomplete al configurar el select con una function para realizarse al seleccionar uno de los valores no se lanza si se selecciona con el ratón, si lo hacemos mediante el intro si que accede y funciona correctamente.

**Comment by hmartinez85** [comment]
Buenos días,

Puedes poner tu llamada al método para reproducirlo, gracias un saludo.

**Comment by jortizza** [comment]
// Autocomplete filtro identificador familias
         $("#"+options.scope+"_familyid_procedure_input").rup_autocomplete({
           source: CTX_PATH + "family/autocompleteAll/remote",
           sourceParam: {
             label: "familyname"+$.rup_utils.capitalizedLang(),
             value: "familyid",
           },
           select:function(){
             var value=$("#"+options.scope+"_familyid_procedure_input").rup_autocomplete("getRupValue");
             _comprobarOficio(value);
           },
           contains : true,
           menuMaxHeight: 325,
           minLength:3,
           combobox: true,
           width: 530
         });
