### ISSUE TITLE
[inlineEdit] + [contextMenu] v3.4.0

### ISSUE THREAD

**Issue by Menengol** [UDA-EJIE/udaRUP#112]
Hola,

Cuando usamos el menú contextual en una tabla de edición en línea con las operaciones por defecto del toolbar, al añadir o editar desde el menú contextual, se ejecutan dichas operaciones automáticamente sin dar la posibilidad al usuario de añadir o editar nada.

Al editar ejecuta directamente la edición del registro sin modificar nada, mostrando el feedback de que la operación se ha ejecutado correctamente.
Al añadir, como tenemos validaciones de campos obligarorios, muestra directamente los errores de las validaciones.

Gracias y un saludo

**Comment by hmartinez85** [comment]
Con la resolución de la issue #103, se soluciona esta issue.

Fix #112
