### ISSUE TITLE
[Tabs] Evento close da un error al hacer el refresh y si  la propiedad close es false duplica el titulo

### ISSUE THREAD

**Issue by jortizza** [UDA-EJIE/udaRUP#116]
Al pulsar sobre el icono del close y ejecutarse el evento on close se produce un error en el código de rup

$('span.ui-icon-close').on('click', function () {

					var tabContentId = $(this).parent().attr('href');
					$(this).parent().parent().remove(); //remove li of tab
					$(tabContentId).remove(); //remove respective tab content

					**(tabs.parent()).tabs('refresh');**
				});
rup.tabs.js:356 Uncaught TypeError: tabs.parent is not a function

También he comprobado que al estar la pestaña activa se oculta el icono pero se puede seguir pulsando cerrando la pestaña no recargando ninguna otra.

Y al deshabilitar la opción del close a false para evitar el error en el evento on close que me afecta a el resto de acciones de la aplicación me duplica el titulo de la pestaña.
![image](https://user-images.githubusercontent.com/26750799/42619729-1e8eaafc-85b9-11e8-8e1b-83488c9af559.png)

**Comment by hmartinez85** [comment]
Hola, puedes poner la llamada al tab y en que versión de UDA estas?.

Gracias.

**Comment by jortizza** [comment]
La llamada es esta

 tabs.rup_tabs("addTab",{
             idTab: tabs.attr("id"),
             lengthLiteral:20,
             close:true,
             position: plugin.settings.position,
             label: visorConfig.title,
             layer: "#"+visorConfig.divProcedimiento.attr("id")
          });           

Estamos en la versión 3.5 de UDA
