### ISSUE TITLE
[inlineEdit] No guarda mantenimientos con edición en linea, error versión 3.5

### ISSUE THREAD

**Issue by jortizza** [UDA-EJIE/udaRUP#117]
Con la actualización de rup a la versión 3.5 no es posible guardar registros en los mantenimientos con edición en linea.

Si volvemos a la versión 3.4 si que nos funciona.

**Comment by xaabi6** [comment]
Aupa @jortizza, tras probarlo en la maqueta de UDA 3.5.0, he podido ver que el guardado solo funciona cuando se realiza a través del teclado (con la tecla "ENTER").

Después, le eché un ojo a los commits realizados entre las versiones 3.4.0 y la 3.5.0 que afectasen al "inline edit", y he podido ver, que el fallo es ocasionado por una corrección que se aplicó en el commit 858322c57055082d9ae5ded79f31b60c6aa8f5ba

Por lo tanto, como workaround de mientras arreglamos el problema, revirtiendo ese commit el botón de guardado volvería a funcionar a costa de volver a hacer fallar el "rup_date".
