### ISSUE TITLE
[UDA][Validaciones] Error en la gestión automática de errores de validación

### ISSUE THREAD

**Issue by ma-santamaria** [UDA-EJIE/udaRUP#119]
Según la documentación de UDA, al realizar una validación automática mediante `@Validated`, ha de obtenerse una respuesta 406 (_Not Acceptable_) en caso de que existan errores de validación.

Sin embargo este no es el caso si los únicos errores de validación se producen por restricciones definidas a nivel de clase, ya que se obtiene una respuesta 200 (_Ok_).

**Comment by hmartinez85** [comment]
Buenos días,

Puedes poner tus declaraciones @validated , las defines solo en las entidades? o en el controller?.

Un saludo.

**Comment by ma-santamaria** [comment]
Buenos días,

la validación se realiza sólo en el controlador; añado un ejemplo que permite observar el comportamiento descrito:

BeanValidado.java:
```java
@CheckEsElDoble
public class BeanValidado {

   private int unNumero;
   private int otroNumero;

   public BeanValidado() {
   }

   public int getUnNumero() {
      return unNumero;
   }

   public void setUnNumero(int unNumero) {
      this.unNumero = unNumero;
   }

   public int getOtroNumero() {
      return otroNumero;
   }

   public void setOtroNumero(int otroNumero) {
      this.otroNumero = otroNumero;
   }

}
```

CheckEsElDoble.java:
```java
@Target({ TYPE, ANNOTATION_TYPE })
@Retention(RUNTIME)
@Constraint(validatedBy = { EsElDobleValidator.class })
@Documented
public @interface CheckEsElDoble {

   String message() default "otro no es el doble de uno";

   Class<?>[] groups() default {};

   Class<? extends Payload>[] payload() default {};

}
```

EsElDobleValidator.java
```java
public class EsElDobleValidator implements ConstraintValidator<CheckEsElDoble, BeanValidado> {

   @Override
   public void initialize(CheckEsElDoble constraintAnnotation) {
   }

   @Override
   public boolean isValid(BeanValidado value, ConstraintValidatorContext constraintContext) {
      if (value == null) {
         return true;
      }

      return value.getOtroNumero() == value.getUnNumero() * 2;
   }

}
```

ValidameController.java:
```java
@Controller
@RequestMapping(value = "/validame")
public class ValidameController {

   @RequestMapping(value = "/automatico", method = RequestMethod.GET)
   public ResponseEntity<Boolean> pruebaValidacionAutomatica(@Validated BeanValidado beanValido) {
      return new ResponseEntity<Boolean>(Boolean.TRUE, HttpStatus.OK);
   }

}
```

Si se realiza la siguiente llamada `<servidor app>/validame/automatico?unNumero=2&otroNumero=5` se obtiene como respuesta un 200 (OK); cuando debería obtenerse un 406 (Not Acceptable). Cabe mencionar, que a pesar de obtener una respuesta OK sí se produce la excepción asociada a la validación fallida.

Saludos.

**Comment by hmartinez85** [comment]
Hola,

Con @RequestBody, y haciendo una petición ajax debería responder el 406.

Como haces la llamada desde url? en ese caso devuelve 200.

Un saludo

**Comment by ma-santamaria** [comment]
Hola,

en caso de usar `@RequestBody` tampoco funciona correctamente.

Después de actualizar a la versión 3.5 el comportamiento que obtenemos ha cambiado, ahora siempre se obtiene una respuesta 200, indistintamente de si se producen errores de validación globales (restricciones a nivel de clase) o en un campo del bean.

La respuesta 200 parece deberse a que el manejador de excepciones siempre redirige a la página de error genérico.

Nuestra configuración para las validaciones es la siguiente:

mvc-config.xml (fragmento):
```xml
<bean class="com.ejie.x38.control.exception.MvcExceptionResolverConfig"></bean>

<bean id="validator" class="org.springframework.validation.beanvalidation.LocalValidatorFactoryBean" >
	<property name="validationMessageSource" ref="messageSource"/>
</bean>
```

validation-config.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.springframework.org/schema/beans
		http://www.springframework.org/schema/beans/spring-beans-3.2.xsd">	
				
	<!-- Proporciona la API de validaciones de UDA -->
	<bean id="validationManager" class="com.ejie.x38.validation.ValidationManager" />
	<!-- Controller que permite la validación de una propiedad de un bean -->
	<bean id="validateController" class="com.ejie.x38.validation.ValidationController" />
</beans>
```

No tenemos registrado ningún `@ExceptionHandler` propio en la aplicación. No hemos visto que sea necesaria ninguna configuración adicional en la documentación.

Si se modifica el ejemplo de la siguiente manera se debería poder comprobar el comportamiento descrito:

BeanValidado.java:
```java
@CheckEsElDoble
public class BeanValidado {

   private int unNumero;
   private int otroNumero;
   @Max(1)
   @Min(1)
   private int unoYNadaMasQueUno;

   public BeanValidado() {
   }

   public int getUnNumero() {
      return unNumero;
   }

   public void setUnNumero(int unNumero) {
      this.unNumero = unNumero;
   }

   public int getOtroNumero() {
      return otroNumero;
   }

   public void setOtroNumero(int otroNumero) {
      this.otroNumero = otroNumero;
   }

   public int getUnoYNadaMasQueUno() {
      return unoYNadaMasQueUno;
   }

   public void setUnoYNadaMasQueUno(int unoYNadaMasQueUno) {
      this.unoYNadaMasQueUno = unoYNadaMasQueUno;
   }

}
```

ValidameController.java:
```java
@Controller
@RequestMapping(value = "/validame")
public class ValidameController {

   @RequestMapping(value = "/automatico", method = RequestMethod.GET)
   public ResponseEntity<Boolean> pruebaValidacionAutomatica(@Validated BeanValidado beanValido) {
      return new ResponseEntity<Boolean>(Boolean.TRUE, HttpStatus.OK);
   }

   @RequestMapping(value = "/automaticobody", method = RequestMethod.POST)
   public ResponseEntity<Boolean> pruebaValidacionAutomaticaBody(@Validated @RequestBody BeanValidado beanValido) {
      return new ResponseEntity<Boolean>(Boolean.TRUE, HttpStatus.OK);
   }

}
```

Pruebas realizadas | Esperado | Obtenido
------------------ | -------- | --------
GET `<servidor app>/validame/automatico?unNumero=2&otroNumero=5&unoYNadaMasQueUno=1` | 406 | 200
GET `<servidor app>/validame/automatico?unNumero=2&otroNumero=5&unoYNadaMasQueUno=2` | 406 | 200
GET `<servidor app>/validame/automatico?unNumero=2&otroNumero=4&unoYNadaMasQueUno=2` | 406 | 200
POST `<servidor app>/validame/automaticobody` {unNumero: 2, otroNumero: 5, unoYNadaMasQueUno: 1} | 406 | 200
POST `<servidor app>/validame/automaticobody` {unNumero: 2, otroNumero: 5, unoYNadaMasQueUno: 2} | 406 | 200
POST `<servidor app>/validame/automaticobody` {unNumero: 2, otroNumero: 4, unoYNadaMasQueUno: 2} | 406 | 200

Saludos.

**Comment by hmartinez85** [comment]
Hola,

Eso que has puesto es correcto ya que las validaciones las gestiona así el propio spring, pero si quitas la validación de clase y dejas solo las de propiedad devuelve el error 406.
Ejemplo
![image](https://user-images.githubusercontent.com/34453480/43633243-ef43890a-9708-11e8-8f35-9a982979c5f1.png)

**Comment by hmartinez85** [comment]
Espero haberlo explicado correctamente.Adjunto modificación de tu código:
![image](https://user-images.githubusercontent.com/34453480/43633522-c209a05e-9709-11e8-933d-9d203b108ad2.png)

![image](https://user-images.githubusercontent.com/34453480/43633537-cd70e646-9709-11e8-8e2f-526023fa3c50.png)

Un saludo

**Comment by ma-santamaria** [comment]
Hola,

después de realizar alguna comprobación más nos hemos percatado de que al realizar las pruebas no establecíamos la cabecera `X-Requested-With`

Repitiendo las pruebas con dicha cabecera establecida obtenemos lo siguiente:

Pruebas realizadas | Esperado | Obtenido
------------------ | -------- | --------
GET `<servidor app>/validame/automatico?unNumero=2&otroNumero=5&unoYNadaMasQueUno=1` | 406 | 200 :heavy_multiplication_x:
GET `<servidor app>/validame/automatico?unNumero=2&otroNumero=5&unoYNadaMasQueUno=2` | 406 | 406 :heavy_check_mark:
GET `<servidor app>/validame/automatico?unNumero=2&otroNumero=4&unoYNadaMasQueUno=2` | 406 | 406 :heavy_check_mark:
POST `<servidor app>/validame/automaticobody` {unNumero: 2, otroNumero: 5, unoYNadaMasQueUno: 1} | 406 | 200 :heavy_multiplication_x:
POST `<servidor app>/validame/automaticobody` {unNumero: 2, otroNumero: 5, unoYNadaMasQueUno: 2} | 406 | 406 :heavy_check_mark:
POST `<servidor app>/validame/automaticobody` {unNumero: 2, otroNumero: 4, unoYNadaMasQueUno: 2} | 406 | 406 :heavy_check_mark:

En los casos correctos, se obtiene siempre la respuesta esperada:

```javascript
{"rupErrorFields":
    {
    "CheckEsElDoble":["otro no es el doble de uno"],
    "unoYNadaMasQueUno":["tiene que ser menor o igual que 1"]
    }
}
```
o:

```javascript
{"rupErrorFields":
    {
    "unoYNadaMasQueUno":["tiene que ser menor o igual que 1"]
    }
}
```

Con esta situación no parece claro que la gestión de las validaciones sea coherente, el comportamiento lógico sería obtener la misma respuesta (406) para el mismo caso (datos no validos). Esto evidentemente plantea un problema para el tratamiento de la respuesta.

Saludos.
