### ISSUE TITLE
[rup_dialog] Al intentar asignar el title con un setOption no funciona

### ISSUE THREAD

**Issue by jortizza** [UDA-EJIE/udaRUP#122]
Al intentar cambiar el title de un dialogo con la función setOption no funciona.

En el código de rup he visto este comentario
//A raíz de un bug del plug-in subyacente, el cambio del titulo se hace a mano (en caso de que se corrija el error esto sorbería y habría que borrarlo)

Quitando ese código funciona correctamente pero no se si es lo correcto y para que se tenga en cuenta en siguientes versiones

**Comment by xaabi6** [comment]
Hola @jortizza.

He estado revisando el código, tanto en UDA 3.5.0 como en versiones anteriores y he llegado a la conclusión de que la parte que compone el "else" sobra.

De entrada no funciona porque busca un id que ningún elemento tiene. Además, si cambias el selector para que busque por una clase, consigues que cambie el título pero una vez haces la llamada mediante el `rup_dialog("getOption","title");` te devuelve el valor anterior ya que solo se ha cambiado el texto del dom.

Dicho esto en el siguiente commit queda corregido: 8083ba37aa8055aa44e8eaf6e08d4a9570a36bb0

Un saludo y gracias por habernos hecho saber de este problema.
