### ISSUE TITLE
[rup_combo] Asignar tamaño con porcentajes

### ISSUE THREAD

**Issue by OmairaF** [UDA-EJIE/udaRUP#127]
Estoy definiendo el width del rup_combo mediante porcentajes (width: "60%"). Visualmente es correcto, coge el tamaño determinado, pero cuando se muestran las opciones haciendo click sobre el combo, el listado no se adapta al tamaño de este.
Con el atributo menuWidth, he conseguido que la anchura del listado de opciones se adapte al texto más largo de esta, pero poco más.
Obviamente, si al combo le doy un tamaño en píxeles, todo funciona correctamente...
¿Es posible que exista algún atributo o algo para trabajar con porcentajes? 

![captura](https://user-images.githubusercontent.com/10741516/48834969-5a838b80-ed7f-11e8-9458-b2592026fbfd.PNG)

Gracias.

**Comment by xaabi6** [comment]
Hola @OmairaF, el problema era que el ancho no se estaba aplicando al contenedor de la lista, entonces, solo funcionaba correctamente si se aplicaba el ancho en pixeles.

El fallo queda corregido en el siguiente commit: https://github.com/UDA-EJIE/udaRUP/commit/0d6482000c10832cafa004be6708c03f2bd1184a

Un saludo
