### ISSUE TITLE
Error multifilter

### ISSUE THREAD

**Issue by optimoprimo** [UDA-EJIE/udaRUP#128]
Error en la generación del multfilter del rup_table.

Desde la versión 3.x de rup no conseguimos generar el componente de multifilter correctamente, ya que el componente rup_autocomplete genera incorrectamente el posicionamiento de los elementos ul que genera, posicionandolo por detras del modal del multifilter.

**Comment by xaabi6** [comment]
Hola @optimoprimo, ¿en que versión de UDA estaís actualmente?

**Comment by optimoprimo** [comment]
La versión 3.5

**Comment by xaabi6** [comment]
Échale un vistazo a nuestra aplicación de ejemplo ya que a nosotros nos funciona bien (versión 3.6):
http://www.ejie.eus/x21aAppWar/table/configurable
http://www.ejie.eus/x21aAppWar/tableLegacy/formEdit
