### ISSUE TITLE
Autocomplete  Error accentFolding

### ISSUE THREAD

**Issue by optimoprimo** [UDA-EJIE/udaRUP#129]
Por defecto el componente de autocomplete de uda tiene el atributo accentFolding a true, pero surge un problema al cambiar este campo a true, y que impide seleccionar un valor.

El objeto data que contiene el array asociativo "label"-"value" que utiliza el componente, genera la key segun el texto, este en mayúsculas o en  minusculas. Pero con el atributo accentFolding a true siempre se genera en minusculas, ya que sufre un tratamiento antes ($.rup_utils.normalize). 

El problema surge al recuperar el label del campo seleccionado:

if (loadObjects[$.rup_utils.normalize(autoCompObject.val())] !== undefined) en la linea 935.

Esta linea siempre intenta buscar en el array asociativo la clave normalizada, independientemente del accentFolding. Lo que generar que siempre se entre por el  ELSE correspondiente, y no se seleccione ningún valor.

**Comment by xaabi6** [comment]
Hola @optimoprimo, he estado probando y con el siguiente commit no sufro el problema que comentáis: 605e6fb45da381467f4c80f0b57d55c3e5b16568

¿Podrías echarle un vistazo? Gracias y a la espera quedo :)

**Comment by optimoprimo** [comment]
Hola.  Como esta ahora mismo no funciona. La idea es correcta pero estáis devolviendo el la clave del array asociativo en vez del valor. Entiendo que la ultima linea debería ser:

$('#' + settings.id).attr('rup_autocomplete_label', loadObjects[autoCompObject.val()]);

De esta forma accedemos al valor.

**Comment by xaabi6** [comment]
Tienes razón, queda corregido en el siguiente commit: d895c7a0398f17d31e23e27666922443e38efde4

**Comment by xaabi6** [comment]
He hecho unos cambios más que he visto que eran necesarios, en los siguientes commits los puedes ver: 1ab3d75f69a5a6b66338326d70cb1529eaaafdfe y cc2a7467662be580be2dc54614923ae9ab806e6f

**Comment by optimoprimo** [comment]
En el commit 1ab3d75 falta hacer un cambio:

En lo que es ahora la linea 942 falta
$('#' + settings.id).val(loadObjects[(autoCompObject.val())]);

Si no el value que deja al abandonar el combo no es el correcto, sino el label.

**Comment by xaabi6** [comment]
> 
> 
> En el commit [1ab3d75](https://github.com/UDA-EJIE/udaRUP/commit/1ab3d75f69a5a6b66338326d70cb1529eaaafdfe) falta hacer un cambio:
> 
> En lo que es ahora la linea 942 falta
> $('#' + settings.id).val(loadObjects[(autoCompObject.val())]);
> 
> Si no el value que deja al abandonar el combo no es el correcto, sino el label.

Ya hice esa corrección, la puedes encontrar en el commit https://github.com/UDA-EJIE/udaRUP/commit/cc2a7467662be580be2dc54614923ae9ab806e6f
