### ISSUE TITLE
[rup_combo] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by smartinez081** [UDA-EJIE/udaRUP#130]
Con el cambio de la version a la 3.6 nos ha surgido el siguiente problema:

![image](https://user-images.githubusercontent.com/1449112/50075495-68da9100-01df-11e9-8eaf-408912a72e25.png)

Si en la funcion change de un combo haces un clear de otro cuando no tiene el atributo selected en la definicion del componente da un error de **Maximum call stack size exceeded**.
La definicion de los mismos es simple.
![image](https://user-images.githubusercontent.com/1449112/50075580-a3dcc480-01df-11e9-80cb-97d3c0da3ba8.png).

Si se define el **selected:""** funciona correctamente pero entendemos que este atributo no es obligatorio en la definicion del mismo.

Un saludo

**Comment by hmartinez85** [comment]
Cerrado con los cambios de la versión 3.7.0
