### ISSUE TITLE
[rup_combo] Combo Agrupado

### ISSUE THREAD

**Issue by smartinez081** [UDA-EJIE/udaRUP#131]
Con el cambio de la version a la 3.6 nos ha surgido el siguiente problema:
![image](https://user-images.githubusercontent.com/1449112/50208717-3a40ef80-0372-11e9-835e-839ce3b442d2.png)

Cuando se le indica a un combo agrupado el atributo blank mete muchos registros en blanco y un label "label".

La respuesta del servicio es correcta.

![image](https://user-images.githubusercontent.com/1449112/50208841-8e4bd400-0372-11e9-819a-92ae6cdb33ae.png)
Un saludo.

**Comment by xaabi6** [comment]
Aupa @smartinez081, revisa tu archivo "**jackson-config.xml**" y dentro del bean con id "udaModule", faltará por añadir el modelo. Te dejo un ejemplo:

![imagen](https://user-images.githubusercontent.com/22637294/50272056-dd5b3d00-0436-11e9-832a-16a98c243605.png)

No obstante, le echaremos un vistazo al plugin, ya que generando un mantenimiento debería de encargarse de añadirlo.

**Comment by smartinez081** [comment]
Hola @xaabi6 ya estaba añadido en el **archivo "jackson-config.xml"**, en las versiones anteriores como en la version 2.X se mostraba correctamente. El problema no es que se muestren todos en blanco, se añade una agrupación mas con elementos en blanco.

![image](https://user-images.githubusercontent.com/1449112/50331278-68ebd100-04fe-11e9-861e-71076666a50b.png)

La respuesta a la peticion ajax para recuperar los datos a mostrar los devuelve correctamente.
![image](https://user-images.githubusercontent.com/1449112/50331314-7e60fb00-04fe-11e9-9550-abd44fbb7fd3.png)

Un saludo
