### ISSUE TITLE
[rup_table-masterDetail] Al añadir o editar no se envía bien la pk del master (v3.6.0)

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#134]
Estamos teniendo problemas a la hora de hacer unas tablas MasterDetail. Al intentar dar de alta un "hijo" nos esta enviando la pk del padre de forma incorrecta y no esta llegando al Controller, lo manda aplicando un "unnest".

En la tabla "hijo" tenemos definido el padre y su pk de la siguiente forma:

`		
masterDetail:{
       master: "#usoPredominante",
       masterPrimaryKey: ["padre.idUsoPredominante"]
},
`

Al realizar el guardado de un alta, recupera de forma correcta la pk del padre, de forma anidada y al enviarlo en la llamada ajax, justo antes le aplica un unnest con lo que la propiedad se manda sin anidar.

![image](https://user-images.githubusercontent.com/11626735/52335403-9e8f3f80-2a02-11e9-9987-a7126730f9da.png)

En la edición, ocurre lo mismo.

He intentado mirar como lo tenéis en la x21 ya que parece que tenéis el mismo caso con comarca-localidad pero el ejemplo de rupTable no esta funcionando (no salen botones, los formularios de edición no tienen campos...),, aun así, lo envía de la misma forma:

![image](https://user-images.githubusercontent.com/11626735/52335741-6a684e80-2a03-11e9-817d-7ee53bf5c398.png)

**Comment by hmartinez85** [comment]
Hola, acabo de ejecutar un ejemplo:
![image](https://user-images.githubusercontent.com/34453480/52411165-1761ca80-2adb-11e9-8dda-6b633709d665.png)

![image](https://user-images.githubusercontent.com/34453480/52411021-9a365580-2ada-11e9-89b7-303e87dfed2c.png)

Y al hacer un alta está llegando el padre también. Nuestro controller es el siguiente:
![image](https://user-images.githubusercontent.com/34453480/52411104-d9fd3d00-2ada-11e9-91b8-86149c3f323a.png)

Si es cierto que en la x21 no esta funcionando aunque ya lo tenemos solucionado y en la próxima versión saldrá, igual te falta algo más en el formulario.
Si te entendido bien vuestro problema es que padre.idUsoPredominante cuando envía el 30 no llega al controller.
Yo no consigo reproducir este error puesto que llega al controller sin problemas.

Un saludo.

**Comment by GardiHuts** [comment]
Hola, 
podrías pasarme el código del formulario y del js? No consigo que tenga ese comportamiento sin informar yo mismo la pk en el formulario.
Viendo la request de tu ejemplo me da la impresión que estáis informando el code de la comarca en el formulario, ya que es el mismo resultado que yo consigo en  una edición.

comarca.code: "1"  <-- Lo que envía el plugin (no se serializa en el controller)
comarca: {code: "1"}  <-- Lo que viene del formulario (correcto)

Por eso me gustaría ver vuestro ejemplo para poder ver que es lo que estoy haciendo mal.

Gracias

**Comment by hmartinez85** [comment]
Si quieres dame tu correo y te lo envió mientras lo subimos a desarrollo , por si ves algo que te falte.

**Comment by hmartinez85** [comment]
Se deja url del ejemplo:
https://www.ejie.ejiedes.eus/x21aAppWar/tableLegacy/masterDetail
