### ISSUE TITLE
filter con rup_autocomplete

### ISSUE THREAD

**Issue by AmandaL89** [UDA-EJIE/udaRUP#135]
Hola, 
Estamos intentando hacer un filtro con el rup_autocomplete remoto.
La búsqueda nos la hace bien pero nos bloquea la tabla.
El error que sale en la consola es:
SCRIPT5007: No se puede obtener valor de la propiedad 'tagName': el objeto es nulo o está sin definir 
rup.min-2.4.5.js, Línea 890 Carácter 7646

¿Como podemos solucionarlo?

**Comment by hmartinez85** [comment]
Hola @AmandaL89 puedes adjuntarnos tu código y algún pantallazo para saber bien el caso exacto del error.

Un aludo.
