### ISSUE TITLE
 DELETE de rup_table no muestra error en su feedback

### ISSUE THREAD

**Issue by bilopavi** [UDA-EJIE/udaRUP#141]
Hola,

Tengo un rup_table en un diálogo que se abre desde un formulario detalle(otro diálogo) de otro rup_table.

Al ejecutar la operación delete del rup_table, da un error de lógica de negocio y el error no se muestra en el feedback del propio rup_table, si no que se ve en el primer feedback que encuentra el DOM dentro de un dialogo visible.

La función donde está programado es showErrorToUser

[https://github.com/UDA-EJIE/udaRUP/blob/master/src/rup.base.js#L593]

![captura](https://user-images.githubusercontent.com/15363919/53619613-3215f380-3bf0-11e9-96df-2d57110cf4b8.JPG)

Lo he solucionado implementando la función error para la acción delete de mi rup_table

`deleteOptions:{
    reloadAfterSubmit:true,
    ajaxDelOptions:{
        error:function (xhr, textStatus, errorThrown){
            var feedback_props = {
                    delay: null
                },
            feedback_principal = $('#' + idTabla +'_feedback' ),
            errorText = $.rup.rupAjaxDefaultError(xhr, textStatus, errorThrown);
            
            // Mostramos el error en el feedback
            feedback_principal.rup_feedback('option', feedback_props);
            feedback_principal.rup_feedback('set', errorText, 'error');
            feedback_principal.rup_feedback('show');
        }
    }
}`
![captura](https://user-images.githubusercontent.com/15363919/53620543-a605cb00-3bf3-11e9-9eae-4d84a27b5dd9.JPG)

De esta forma consigo que se muestre el error donde quiero, pero no sé si debería ser RUP quien se encargue de sacar el error en el feedback correcto ya que es una operación genérica del rup_table.

Un saludo

**Comment by hmartinez85** [comment]
El error es con edición en linea,no?

**Comment by bilopavi** [comment]
no, es un rup_table con formulario

Primero hay un rup_table, se edita y abre un formulario. En ese formulario hay un botón que abre un diálogo que contiene otro rup_table. Es en ese rup_table cuando al ejecutar el botón eliminar, el mensaje sale en el feedback del formulario detalle (capa inferior), porque es el primer feedback que encuentra al ejecutar 

var dialog_feedbacks = $('.ui-dialog:visible .rup-feedback') SELECTOR DE FEEDBACKS,
feedbacks = dialog_feedbacks.length !== 0 ? dialog_feedbacks : $('.rup-feedback');
// Se comprueba si existe un rup_feedback en la pagina
if (feedbacks.length != 0) {
var feedback_props = {
delay: null
},
//Si existen rup_feedbacks cogemos el primero
feedback_principal = $('#' + feedbacks[0].id);
                // Mostramos el error en el feedback
       feedback_principal.rup_feedback('option', feedback_props);
feedback_principal.rup_feedback('set', errorText, 'error');
feedback_principal.rup_feedback('show');
}
