### ISSUE TITLE
Botón editar no ejecuta llamada GET (V.3.6.0)

### ISSUE THREAD

**Issue by unaimartinez** [UDA-EJIE/udaRUP#142]
Hola,

Tengo un componente datatable el cual tiene una botonera la cual contiene el botón "Editar". Cuando se pulsa el botón no se realiza llamada alguna (entiendo que debería ejecutarse un GET) por lo que cuando se carga el detalle no dispongo de todos los datos.

Un saludo.

**Comment by hmartinez85** [comment]
Hola,

Podrías ponerme el código de tu llamada para verlo y la jsp.

Gracias. Un saludo.

**Comment by unaimartinez** [comment]
Hasta ahora el componente "rup_table" estaba programado parar ejecutar una llamada ajax de tipo GET, en la que se pasaba el id del registro seleccionado en la url. Te pongo un ejemplo de la llamada generada en otra aplicación.

> Request URL: http://www.vas.jakina.ejiedes.net/m62abAdquisicionWar/mtoadquisicion/adquisicion/107201?_=1552563981005
> Request Method: GET
> Status Code: 200 OK
> Remote Address: 10.190.16.14:80
> Referrer Policy: no-referrer-when-downgrade

Precisamente el problema que tenemos es que con el componente "datatable" que estamos usando no se ejecuta esa llamada.
