### ISSUE TITLE
Llamadas operaciones añadir, editar y eliminar [V.3.6.0]

### ISSUE THREAD

**Issue by unaimartinez** [UDA-EJIE/udaRUP#145]
Hola,

estoy desarrollando un mantenimiento que tiene un formulario de detalle tipo "multipart-data", ya que se requiere upload de ficheros. Estoy desarrollando las operaciones de añadir, modificar y eliminar pero me encuentro con la siguiente problemática.

- Las operaciones de añadir y modificar ejecutan la misma llamada ajax de tipo POST. Esto no es correcto, en el caso de la operación de añadir debería ser una llamada POST y en el caso de modificar debería ser una llamada PUT.

- Las operación de borrado ejecuta una llamada ajax de tipo POST, pasando como parámetro el id del elemento a borrar, en este caso entiendo que debería ser una llamada de tipo DELETE.

Un saludo.

**Comment by hmartinez85** [comment]
Hola Unai puedes mandarme tu mail a hmartinez@euro-help.es para hablar mejor.

Gracias

**Comment by unaimartinez** [comment]
Claro!!! Te lo acabo de enviar.
