### ISSUE TITLE
[UDA-EJIE/udaRUP] El botón guardar y continuar al añadir [3.7.1]

### ISSUE THREAD

**Issue by unaimartinez** [UDA-EJIE/udaRUP#151]
Hola,

La primera vez que se añade un registro en un mantenimiento con el botón "Guardar y continuar" se ejecuta una llamada ajax de tipo POST. Si se vuelve a añadir un elemento se ejecuta una llamada PUT en vez de POST. Entendemos que siempre que se vaya a añadir un elemento se debería ejecutar una llamada POST.

Un saludo.

**Comment by hmartinez85** [comment]
Después del primer guardado se cierra el dialogo y se vuelve a añadir? o es directamente dentro del mismo dialogo?.

Un saludo.
