### ISSUE TITLE
UDA 3.7.2 Multiselect 

### ISSUE THREAD

**Issue by oierjim** [UDA-EJIE/udaRUP#152]
Hola

RUP_DATATABLES

Siguiendo la aplicación de demo, poniendo el multiselect, el seleccionar todos no funciona si definimos las columnas ya que alguna queremos ocultar.
En la demo funciona porque columns no esta definido, de hecho en la demo aparece un colModel que es la definicion de las rup_table NO las rup_datatables.

Hemos mirado el rup.js y en la siguiente linea:
options.columns = options.columns || $self._getColumns(options);

dentro del apartado $.fn.rup_datatable('extend', {
_initOptions

En el caso de que no este definido el options y se quieran mostrar todas las columnas definidas en jsp perfecto pero si no, no hay multiselect (seleccionar TODOS)

pd. relacionado con la otra incidicencia que abrí, si hay dos tablas el multiselect no funciona muy bien.

**Comment by lapitzasclub** [comment]
No conseguimos reproducir el problema de multiselección, a lo mejor no estamos entendiendo bien el problema.

Nosotros hemos ocultado la columna como se especifica en la [documentación de la propia librería de datatables](https://datatables.net/reference/option/columns.visible)

**Comment by oierjim** [comment]
Hola:
Seguro que no me he explicado bien.
Intento de nuevo.

En vuestra demo en esta url: http://www.ejie.eus/x21aAppWar/table/configurable
aparece una tabla con multiselección.  Esa tabla las columnas las estáis definiendo con colModel (que no se tiene que usar para las datatables eso era para las jqgrid) 
Si nosotros queremos formatear una columna de datatable hay que usar el  **plugins.columns** que es el que antes era el colmodel y ahora tenemos que llamar al render.

Como en vuestro ejemplo se no se formatea nada y el único css que hay es un check con un tic, casualmente como esta en la jsp definida todo el trozo de colModel no sirve para nada. Y por suerte  en el trozo de codigo donde va a pintar el checbox del multiselect que indico arriba como en vuestro ejemplo **no tenéis** definido el **columns**  nuevo de datables os funciona, si se define uno ya no se muestra el multiselect.

**Comment by hmartinez85** [comment]
Buenas @oierjim  , el colModel actualmente lo estamos usando tanto para el seeker como para ambos filtros de la tabla, actualmente se puede usar el atributo colummns ya que es una colección y nosotros solo sobrescribimos la posición cero del mismo que corresponde a la multiseleción. Respecto a la tabla anterior hemos cambiando varios aspectos y estamos subiendo los ejemplos y la documentación para que se pueda ver.

un saludo

**Comment by oierjim** [comment]
Nosotros queremos hacer una tabla con multiselección, y que una columna que tiene valores 0 o 1 nos ponga Si o No. Solo lo hemos hecho posible con el columns la propiedad render. Con el formatter es imposible hacer nada. Y el que teneis del checbox no se ejecuta esta cogiendolo desde la jsp.

Si en esta de ejemplo http://www.ejie.eus/x21aAppWar/table/configurable, podeis poner una columna que tome valores si o no pero que internamente tenga 1 o 0, nos valdría.

Gracias

**Comment by hmartinez85** [comment]
Hola, adjunto captura de un ejemplo sencillo que te valdría.
![image](https://user-images.githubusercontent.com/34453480/61273562-1c255b80-a7aa-11e9-81cc-81042a211842.png)

**Comment by xaabi6** [comment]
La duda fue resuelta, por lo tanto, cierro la issue.
