### ISSUE TITLE
[UDA-EJIE/udaRUP] Autocomplete - no muestra todos los resultados al buscar con los mismos caracteres [3.7.1]

### ISSUE THREAD

**Issue by sgurrea** [UDA-EJIE/udaRUP#154]
Hola,

estamos trabajando en el proyecto de Procesos de Provisión y Selección del Gobierno Vasco – Bolsas de Trabajo y nos estamos encontrando un comportamiento extraño en el autocomplete.

Cuando se realiza una búsqueda que contiene los caracteres introducidos que encuentra más de un resultado, si volvemos a buscar por los mismos caracteres, a la hora de mostrar los resultados solo aparecen aquellos que empiezan por dichos caracteres. y vemos que no se vuelve a invocar a BBDD para recuperar los resultados.

Os adjunto un documento con un ejemplo de los que nos está ocurriendo.
[ejemplo_autocomplete.docx](https://github.com/UDA-EJIE/udaRUP/files/3290628/ejemplo_autocomplete.docx)

En el código tenemos definido el autocomplete de la siguiente manera::

$("#bolsa_nombreBolsa_filter_table").rup_autocomplete({
		source : $.rup.CTX_PATH + "combo/autocomplete/bolsa",
		sourceParam : {
			label : "bolsaLabel",
			value : "idBolsaSap"
		},
		contains : false,
		menuMaxHeight : 200,
		accentFolding : false,
		combobox : false,
		minLength : 3
	});

Un saludo

**Comment by lapitzasclub** [comment]
No hemos conseguido reproducir este comportamiento

**Comment by xaabi6** [comment]
Cómo la incidencia no fue reproducible y no se obtuvo respuesta por parte de @sgurrea , cierro la issue.
