### ISSUE TITLE
[rup_table] Problema con ordenación de textos con tildes

### ISSUE THREAD

**Issue by jjjonathansp** [UDA-EJIE/udaRUP#156]
En una tabla, a la hora de ordenar tanto ascendente como de forma descendente una columna, la ordenación se realiza de forma incorrecta en campos que disponen de tildes. Como ejemplo, lo que se puede visualizar en la web demo.
- Ordenación ascendente:
![Ordenacion ascendente](https://user-images.githubusercontent.com/12515119/61371838-f83f4400-a895-11e9-9176-7fb68b5cd63a.png)
- Ordenación descendente:
![Ordenacion descendente](https://user-images.githubusercontent.com/12515119/61371839-f83f4400-a895-11e9-9425-1e2ca1e48557.png)

**Comment by xaabi6** [comment]
Disculpa la demora @jjjonathansp, ya tenemos lista una solución para este problema. Nuestro compañero @escaleramen se encargó de crear un aspecto en la [librería x38](https://github.com/UDA-EJIE/udaLib) que podéis usar incluyendo la siguiente configuración en el fichero ``dao-config.xml`` del proyecto *EarClasses*, este aspecto se asegurará de que el idioma de la sesión de base de datos y weblogic sean el mismo cuando se haga una petición:
```xml
<bean id="nlsLangControl" class="com.ejie.ab74j.util.NlsLangControl">
   <property name="sqls">
         <list>
                <value>ALTER SESSION SET NLS_LANGUAGE= 'SPANISH' NLS_TERRITORY= 'SPAIN'</value>
          </list>
   </property>
</bean>
```

Estará disponible en la próxima versión de UDA, un saludo y gracias por tu paciencia.
