### ISSUE TITLE
Al añadir nuevo registro no recoge el campo definido en la primarykey

### ISSUE THREAD

**Issue by jalzamudio** [UDA-EJIE/udaRUP#16]
En el fichero rup.table.formEdit-2.4.6.js, se ha incorporado un cambio que hace que no recoja el valor introducido en el campo que se define en la propiedad primarykey del rup_table.

El cambio realizado de la versión 2.4.5 a la 2.4.6 ha sido el siguiente:
Se ha comentado la línea 1043 del fichero rup.table.formEdit-2.4.6.js:
switch ((rowid == '_empty'?"clientSide":settings.formEdit.editOptions.fillDataMethod)){

y se ha puesto la siguiente:
switch (settings.formEdit.editOptions.fillDataMethod){

Para que funcione correctamente, he tenido que volver a poner la anterior.

**Comment by enekoza** [comment]
El error se corrige con las modificaciones introducidas en el commit UDA-EJIE/udaDemoApp@8ad1f29 

Se liberará en la siguiente release v2.4.7
