### ISSUE TITLE
Problema con multiseleción y 2 tablas

### ISSUE THREAD

**Issue by hmartinez85** [UDA-EJIE/udaRUP#160]
Si tenemos 2 tablas multiselect, el valor de "nº de elementos selecccionados" no se actualiza correctamente. Seleccionas en una tabla y te cuenta como seleccionados en la otra, sin tener nada marcado.
![fallo1](https://user-images.githubusercontent.com/34453480/69407041-d4888080-0d03-11ea-99f8-b7fa0f0cf509.png)

**Comment by oierjim** [comment]
Hola, he visto que hay una release, preparada para esto. ¿Cuando va a estar disponible?
En la version 4.1 si que añadisteis la corrección de poder meter dos tablas con multiselección, pero esta incidencia e incluso otra que supongo que al abordar esta verías (que se da también en la demo de dos tablas) que al seleccionar todos los elementos de una tabla también se seleccionan en la otra.

Para la versión anterior cambiamos mucho codigo del rup.js para hacerlo funcionar pero como veo que ya hay prevista una release 4.2.0 para una nueva aplicación que tenemos preferimos esperar a la solución oficial.

**Comment by hmartinez85** [comment]
Hola, tenemos la previsión de liberar la versión 4.2.0 entre mañana y la próxima semana.

Un saludo

**Comment by oierjim** [comment]
Muchas gracias.
