### ISSUE TITLE
Table nuevo , error en el responsive

### ISSUE THREAD

**Issue by hmartinez85** [UDA-EJIE/udaRUP#161]
En las tablas de la versión 4.1, para una tabla se van ocultando columnas, según la ventana se hace más pequeña y la tabla no cabe, y aparece un icono (+) para visualizar las columnas no mostradas. Sin embargo, si por ej. necesitamos que haya una columna ocultada por código (como puede ser la del código interno de la tabla en Oracle) el icono (+) sale siempre aun cabiendo todas las columnas en la ventana.
![fallo2](https://user-images.githubusercontent.com/34453480/69407157-28936500-0d04-11ea-83f2-109d8bb4e7ae.png)

**Comment by lapitzasclub** [comment]
Related DataTable issue:
https://github.com/DataTables/Responsive/issues/8
