### ISSUE TITLE
Rup - DEMO - EDIT

### ISSUE THREAD

**Issue by oierjim** [UDA-EJIE/udaRUP#163]
Hola
En la aplicación de Demo, y en nuestra aplicación, utilizando un mantenimiento por defecto con los botones de editar por defecto si un campo de texto contiene el carácter % da un fallo de javascript, no se si con algún carácter más.
![image](https://user-images.githubusercontent.com/3974061/72272597-30e38e80-3629-11ea-8cf0-44a63182d82f.png)

**Comment by xaabi6** [comment]
Hola @oierjim, este tipo de caracteres no son soportados por UDA. Controlaremos el error para que muestre un mensaje que deje claro lo que te acabo de comentar.

Un saludo

**Comment by oierjim** [comment]
Hola @xaabi6, en anterior versión con rup_tables, los popups si que permitían todos los caracteres, de hecho es un campo que no lo han rellenado desde el toolkit y nos llega así. Lo intentaremos escapar modificando el rup.js
