### ISSUE TITLE
[rup_report] Descarga de informes grandes en Chrome

### ISSUE THREAD

**Issue by ihernaez** [UDA-EJIE/udaRUP#164]
En algunas aplicaciones se generan informes de cierto volumen. Cuando estos informes se descargan con `rup_report` desde Chrome la descarga se cancela prematuramente. Esto se debe a que en Chrome el evento ‘successCallback’ de [jquery-fileDownload][jquery.fileDownload] llega cuando la descarga del fichero comienza, pero antes de que haya terminado (se ha probado con la última versión del plugin). Al parecer en otros navegadores (probado en Firefox, IE11, Opera y Safari) el evento llega cuando el informe ya ha terminado de descargarse.

El componente ‘rup_report’, en el método ‘_configureButton’, hace la llamada a ‘jquery-fileDownload’ de la siguiente manera:

```js
//Lanzar petición
$.fileDownload($.rup_utils.setNoPortalParam(button.url), {
    httpMethod: 'POST',
    data: jQuery.rup_utils.unnestjson(data),
    successCallback: function (url) {
        if (dialog.successCallback !== undefined) {
            dialog.successCallback();
        }
        $reportFileWait.rup_dialog('close');
    },
    failCallback: function (responseHtml, url) {
        try{
            if($('#'+$reportFileWait.attr('id')).length > 0) {
                $reportFileWait.rup_dialog('close');
            }
        }
        catch(e){
            console.info('ERROR-----------');
        }
        if($('#' + dialog.errorDiv).length > 0){
            var $reportFileError = $('#' + dialog.errorDiv);
            $reportFileError.rup_dialog({
                type: $.rup.dialog.TEXT,
                autoOpen: false,
                modal: true,
                resizable: false
            });
            if (standarDialog) {
                //Titulo
                $reportFileError.rup_dialog('setOption', 'title', dialog.error.title);
                //Contenido
                $reportFileError.rup_dialog('setOption', 'message', dialog.error.msg);
            }
            $reportFileError.rup_dialog('open');
        }
        if (dialog.failCallback !== undefined) {
            dialog.failCallback(responseHtml, url);
        }
    }
});
```

Es decir, en caso de que descarga haya terminado con exito llama al callback ‘dialog.sucessCallback’ y después cierra el diálogo de espera, y en caso de que la descarga haya fallado cierra el diálogo de espera, muestra el diálogo de error y llama al callback ‘dialog.failCallback’.

El problema viene al cerrar el diálogo de espera, ya que este, definido en el mismo método, se configura de la siguiente manera:

```js
$reportFileWait.rup_dialog({
    type: $.rup.dialog.TEXT,
    autoOpen: false,
    modal: true,
    resizable: false,
    close: function (event, ui) {
        if ($.rup.browser.isIE) {
            //IE
            document.execCommand('Stop');
        } else {
            //Netscape/Mozilla/Firefox
            window.stop();
        }
    }
});
```

La opción ‘close’ define una [función][rup_report dialog close] que detiene cualquier comunicación que esté realizando el navegador, lo que en Chrome cancela la descarga que todavía no ha llegado a completarse. ¿Por qué se hace esto? Esa llamada detendría cualquier comunicación, incluidas aquellas iniciadas en segundo plano por otros componentes de la página, cuando la descarga del informe ha terminado o fallado, por lo que no tiene ninguna utilidad práctica de cara a la descarga del informe en sí y puede afectar a otros procesos en marcha.

La única manera de evitar esta llamada a ‘stop’ cuando la cookie de la descarga se ha recibido (que es lo que detecta ‘jquery-fileDownload’ para confirmar el éxito de la descarga) es sobrescribir el método ‘close’ del diálogo de espera. Por desgracia RUP no proporciona mecanismos para manipular ese diálogo directamente. La única manera es definir el callback ‘dialog.sucessCallback’ por cada informe y, aprovechando que RUP graba a fuego el ID del dialogo de espera:

```js
$("#idTabla").rup_table({
    // ...
    report : {
        // ...
        dialog: {
            successCallback: function() {
                // Informe descargado...
                $('#reportFileWait').dialog('option', 'close', function() {
                    // Evitada llamada a stop()
                });
            }
        }
    },
    ...
});
```

¿Es realmente necesaria la llamada a `stop`? En nuestras pruebas la opción `close` del diálogo puede eliminarse completamente...

[jquery.fileDownload]: https://github.com/johnculviner/jquery.fileDownload
[rup_report dialog close]: https://github.com/UDA-EJIE/udaRUP/blob/f7cdaf8d3fe3bfec743b19598066dc7c61f3f876/src/rup.report.js#L266

**Comment by sergisu** [comment]
Se ha intentado reproducir el problema descrito descargando informes de 100Mb y 200Mb. 
Y no se ha cancelado la descarga en ningún caso.
Aparentemente se lanza el stop() pero no se para la descarga y la petición se resuelve con http 200.

![rup_report](https://user-images.githubusercontent.com/11539034/78685891-a68e8c00-78f2-11ea-920e-65f4c2a11660.gif)


En cualquier caso, limpiaremos la parte de código innecesario.
