### ISSUE TITLE
Datatable 4.2 Editar

### ISSUE THREAD

**Issue by oierjim** [UDA-EJIE/udaRUP#165]
Hola:
Hemos encontrado una combinación que salta un alert warning de DataTable al añadir un registro, sin haber tocado mucho código. Hemos generado el mantenimiento de CRUD normal con el generador de código. Y tenemos una clave primaria compuesta, esas dos columnas no quiero que se muestren en la tabla, y otra columna quiero que renderice con unos valores según el campo de bbdd. Por esto hemos definido un columnDef para ocultar alguna columna y otra con un render especifico.
Luego he cambiado un poco el popup de edición ocultando los campos de primary key ya que estos son autocalculables y el usuario no tiene que verlos.
Haciendo esto ha funcionado el alta pero sale un alert warning de Datatables. Por detrás del warning se ve que el alta esta hecha.
![image](https://user-images.githubusercontent.com/3974061/81693644-7e013100-9460-11ea-9418-9e02371add1c.png)
Revisando el error en la documentación habla de que se le están pasando menos columnas de las que son. Y esto ocurre por tener el columnDef definido que lo necesitamos. En vuestra demo no teneis este caso.
He puesto un breakpoint en el alert y tirando del hilo en el rup.table.editForm al darle a guardar en el metodo _callSaveAjax le llega un row sin las columnas tipo input hidden y en el ajax success de más abajo al hacer dt.row(index).data(rowAux); falla internamente el datatable por tener menos filas de lo especificado. Tampoco entiendo esta parte del ajax success para que se hace ya que la insert ya la ha hecho pero bueno.

Tirando del hilo un poco más ese row que no estaba completo se rellena por arriba (ataTable.editForm.fnOpenSaveDialog) row = _editFormSerialize(idForm); // Verificar los checkbox vacíos.
Y esta función de serializar no tiene encuenta los input hidden

Para tirar para adelante los inputs los he puesto de tipo text y los he ocultado por css, pero no se que implicaciones puede tener todo esto.

En resumen, si defines el columnDef y en el popup de edición tienes una columna de la tabla de input type hidden falla. En vuestra demo aunque pongáis apellido dos, funciona porque no esta el columnDef, esto ultimo ya es según el alert que dice que vayas a una pagina de información del Datatables.

Espero que me haya explicado bien.

**Comment by hmartinez85** [comment]
buenos días, te he entendido perfectamente, por recomendación de seguridad, hemos realizado un pequeño cambio, para que ahora los campos que no quieras enviar tengan la clase 'd-none', en vez de campos hidden, estamos actualizando la documentación para explicar estos cambios debido a que en esta versión, se está metiendo seguridad adicional.
