### ISSUE TITLE
IE11 renderización de inputText con placeholder

### ISSUE THREAD

**Issue by sergisu** [UDA-EJIE/udaRUP#167]
Al incluir el placeHolder en un campo de tipo text, el renderizado no se hace bien en Internet Explorer 11.

Se puede ver en la aplicación de ejemplo: http://www.ejie.eus/x21aAppWar/styleGuide
![inputText_placeholder](https://user-images.githubusercontent.com/11539034/93086109-e6725000-f696-11ea-9d23-61103b55c90a.png)

**Comment by xaabi6** [comment]
Queda arreglado en el commit d17c2a43dd3895f946b0dcf7f940a8164a4f7448.
