### ISSUE TITLE
rup_list - no filtra más si no hay registros

### ISSUE THREAD

**Issue by oierjim** [UDA-EJIE/udaRUP#168]
Hola:
Como se muestra en la imagen de la demo de uda, si el componente uda rup_list al filtrar, si no devuelve resultados, ya no permite volver a filtrar por otros valores, y aparte se queda el gif de cargando para siempre.

![image](https://user-images.githubusercontent.com/3974061/97893563-ba3b8d00-1d31-11eb-99aa-21d0c021e09c.png)

**Comment by oierjim** [comment]
Creo que falta poner:
self.isFiltering.resolve();
self._unlock();
al final del else que pone este comentario // Si no se devuelven resultados

**Comment by xaabi6** [comment]
Efectivamente @oierjim, faltaba por añadir las dos llamadas de las funciones que comentas, gracias 👍
