### ISSUE TITLE
[UDA 4] No se cargan los literales i18n de la aplicación

### ISSUE THREAD

**Issue by McCoy9000** [UDA-EJIE/udaRUP#176]
Al cargar una página de una aplicación UDA 4 los literales propios aparecen como undefined, no así los de UDA. Una vez cargada la página sí que es posible invocar las entradas en ```$.rup.i18n.app```.

Es un error que sucede en la mayoría de ocasiones pero algunas veces sí que carga el archivo de literales antes de renderizarlos. 

He probado a añadir la opción ```async:false``` a la llamada ajax de la función ```getFile_i18n()``` de ```rup.base.js``` y entonces los literales se cargan normalmente.

¿Es posible que hayamos cometido algún error de configuración para poder trabajar con la promesa que se gestiona en ```iniRup()```?
```//Se cargan los literales por defecto
 $.rup.setLiterals().then(function () {
     //Carga de ficheros de literales de la apliaccion
     if (jQuery.rup.WAR_NAME !== '') {
         $.rup.getFile_i18n().then(function () {
             global.initRupI18nPromise.resolve();
         });
     } else {
         global.initRupI18nPromise.resolve();
     }
});

**Comment by sergisu** [comment]
Hola, 
No sé si habéis tenido en cuenta que a partir de la versión 4.1.0, se ha modificado la forma de cargar los estáticos. Lo indica en la página de actualización: 

IMPORTANTE: a partir de la versión 4.1.0 de UDA es necesario hacer uso de la función initRupI18nPromise() para cargar los recursos idiomáticos, se puede encontrar más información en el apartado de la versión 4.1.0.
https://github.com/UDA-EJIE/uda-ejie.github.io/wiki/Actualizar

**Comment by McCoy9000** [comment]
Ese era el problema. Muchas gracias
