### ISSUE TITLE
[css][4.2.2] Errores en la visualización de campos "range"

### ISSUE THREAD

**Issue by jorgeb51** [UDA-EJIE/udaRUP#177]
Hola,
Estamos usando la versión 4.2.2 de RUP, cuyos estilos extienden de bootstrap 4.4.1. Hemos encontrado un par de "fallos" de visualización en los tipos de campo "range". El navegador con el que hemos realizado la prueba es Chrome (88.0.4324.190).
Estos campos se ven con una ligera sombra (`box-shadow`).
Cogiendo el ejemplo de código de la página de bootstrap:
```
<form>
  <div class="form-group">
    <label for="formControlRange">Example Range input</label>
    <input type="range" class="form-control-range" id="formControlRange">
  </div>
</form>
```
Se ve así:
![image](https://user-images.githubusercontent.com/8099641/110445416-5dc0f380-80be-11eb-8e4e-3bb558fa7904.png)

También hay una pequeña diferencia (aunque no tan importante) en cómo se visualizan los límites del rango. Con el css original de bootstrap puedes arrastrar el slide hasta el final del recorrido:
![image](https://user-images.githubusercontent.com/8099641/110446169-2b63c600-80bf-11eb-93f4-ce72c428c81d.png)
Mientras que con el css de rup, el slide tiene el comportamiento 'por defecto' del navegador (no llega a poderse arrastrar hasta el final).
![image](https://user-images.githubusercontent.com/8099641/110447467-8ea22800-80c0-11eb-8c90-e7ddd34cb702.png)

**Comment by xaabi6** [comment]
Ya está corregido @jorgeb51, gracias por avisarnos abriendo esta issue.

Ambos problemas sucedían porque una de nuestras hojas de estilos estaba aplicando ciertos estilos que alteraban el comportamiento por defecto que aplica Bootstrap. En la siguiente versión de UDA tendréis disponible la corrección.
