### ISSUE TITLE
[css][4.2.2] Error en la visualizacion de"input-groups" de bootstrap

### ISSUE THREAD

**Issue by jorgeb51** [UDA-EJIE/udaRUP#178]
Hola,
Estamos usando la versión 4.2.2 de RUP, cuyos estilos extienden de bootstrap 4.4.1. Hemos encontrado un fallo de visualización en los componentes "input-group" de bootstrap. El navegador con el que hemos realizado la prueba es Chrome (88.0.4324.190).
Según la guía de bootstrap (https://getbootstrap.com/docs/4.4/components/input-group/), al incluir el siguiente código html:
```
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">@</span>
  </div>
  <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
</div>

<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <span class="input-group-text" id="basic-addon2">@example.com</span>
  </div>
</div>
```
Debería poder visualizarse los campos de formulario tal que así:
![image](https://user-images.githubusercontent.com/8099641/110472815-22362180-80de-11eb-86e8-c23ad43a0b40.png)
Pero en UDA hay un fallo al adecuar la altura de componente a la del campo input:
![image](https://user-images.githubusercontent.com/8099641/110473096-6fb28e80-80de-11eb-9684-4c41a64a705c.png)

**Comment by xaabi6** [comment]
Ya está corregido @jorgeb51, gracias por avisarnos con la issue.

El problema era que algunas de nuestras hojas de estilos estaban sobrescribiendo los estilos por defecto que aplica Bootstrap. En la siguiente versión de UDA tendréis disponible la corrección.
