### ISSUE TITLE
Combo Inline

### ISSUE THREAD

**Issue by sandresmuniesa** [UDA-EJIE/udaRUP#186]
Buenos dias.
Estoy recibiendo varios errores cuando uso combos en una tabla con la edicion inline y con seleccion simple. 
El primero de ellos es el siguiente y me da al cargar la página. Tengo tambien un combo en el filtro pero funciona correctamente o al menos las busquedas las hace bien.
![imagen](https://user-images.githubusercontent.com/26146519/119346368-6a56f000-bc9a-11eb-9d34-6a2edc050836.png)

Y el segundo es un error que me da al editar o añadir una nueva linea en la talba y que veo que tambien ocurre en la web de ejemplos [http://www.ejie.eus/x21aAppWar/table/configurable](url) cuando configuras la tabla como he comentado. Este por el mensaje creo que esta relacionado con la selección simple
![imagen](https://user-images.githubusercontent.com/26146519/119346522-9bcfbb80-bc9a-11eb-8651-d568fb7761a5.png)

Pongo por aqui el codigo del archivo js, es bastante sencillo. ¿Podeis indicarme si estos errores se deben a un error mio o un error de RUP?
Ya he probado con varios arrays para el combo, actualmente estoy probando con uno "hardcodeado" como en la web de ejemplos. (Disculpad que el código no se copia muy bien formateado)

`  
jQuery(function($){
	arraySectores = [];
	$.getJSON( "http://localhost:7001/ad26aAppWar/contenidosDidacticos/sector", function( data ) {
		console.log(data);
		for (var i=0;i<data.length;i++) {
				arraySectores[arraySectores.length] = data[i];
		}
	});	
	
	/*getSectores =  function(){
		$.getJSON( "http://localhost:7001/ad26aAppWar/contenidosDidacticos/sector", function( data ) {
			console.log(data);
			arraySectores = [];
			for (var i=0;i<data.length;i++) {
					arraySectores[arraySectores.length] = data[i];
			}
			return arraySectores;
		});
	}*/
	
	var combo = [{
		descripcion: '---',
        id: ''
    },
    {
    	descripcion: 'Administrador',
    	id: 'administrador'
    },
    {
    	descripcion: 'Desarrollador',
    	id: 'desarrollador'
    },
    {
    	descripcion: 'Espectador',
    	id: 'espectador'
    },
    {
    	descripcion: 'Informador',
    	id: 'informador'
    },
    {
    	descripcion: 'Manager',
    	id: 'manager'
    }
    ];

	
	let tableColModels = [			
			{ 	name: "id", 
				index: "id", 
				editable: true, 
				hidden: false,
				formoptions: {
                    rowpos: 0,
                    colpos: 1
                }
			},
			{ 	name: "sector", 
				index: "sector_detail_table",
				editable: true, 
				hidden: false,
				width: 140,
                rupType: 'combo',
                rwdClasses: 'hidden-xs hidden-sm hidden-md',
                formatter: 'rup_combo',
                editoptions: {
                    source: $.map(combo, function (elem) {
                        return {
                            label: elem.descripcion,
                            value: elem.id
                        };

                    }),
                    width: '100%',
                    customClasses: ['select-material']
                },
				formoptions: {
                    rowpos: 1,
                    colpos: 1
                }
			},
			{ 	name: "descripcionEuskera", 
				index: "descripcionEuskera", 
				editable: true, 
				hidden: false,
				formoptions: {
                    rowpos: 2,
                    colpos: 1
                }
			},
			{ 	name: "descripcionCastellano", 
				index: "descripcionCastellano", 
				editable: true, 
				hidden: false,
				formoptions: {
                    rowpos: 3,
                    colpos: 1
                }
			},
			{ 	name: "publicado", 
				index: "publicado_detail_table", 
				editable: true, 
				hidden: false,
				width: 60,
                edittype: 'checkbox',
                formatter: 'checkbox',
                rwdClasses: 'hidden-xs hidden-sm hidden-md',
                align: 'center',
                editoptions: {
                    value: '1:0'
                },
                formoptions: {
                    rowpos: 4,
                    colpos: 1
                }
			}
			];

	$("#diccionario").rup_table({
		colReorder: {
		 fixedColumnsLeft: 1
		}
		,colModel: tableColModels
		,primaryKey: "id"
		,filter:{
  	  		id:"diccionario_filter_form",
  	  		filterToolbar:"diccionario_filter_toolbar",
  	  		collapsableLayerId:"diccionario_filter_fieldset"
     	}
    			
    	,inlineEdit:{
         	validate:{ 
    			rules:{
	    				"id":{
							required: false
    					}
    					,
	    				"sector":{
							required: false
    					}
    					,
	    				"descripcionEuskera":{
							required: false
    					}
    					,
	    				"descripcionCastellano":{
							required: false
    					}
    					,
	    				"publicado":{
							required: false
    					}
    					
					}
    		   	}
    				}
       		,select: {
           		activate: true
       		}
    		,seeker: {
    			activate: true
			}
			,buttons: {
				activate: true
			}
			,order: [[ 0, "asc" ]]
	});
	
	
}); `

**Comment by xaabi6** [comment]
Hola @sandresmuniesa, es muy posible que el problema de la carga del combo suceda porque cuando lo intentas inicializar, los recursos idiomáticos no estén cargados y como el componente los necesita tener disponibles, falla. Prueba a insertar tu código dentro de la función `then`:

```js
window.initRupI18nPromise.then(function () {
   // Inserta aquí tu código
});
```

Eso debería solventar el primer problema porque comenzaría a ejecutar el código que hayas definido dentro de la función `then`, una vez la función `initRupI18nPromise` haya devuelto una promesa resuelta indicando que terminó de ejecutarse. 

Respecto al segundo problema, efectivamente, es un fallo de UDA que tenemos solventado y será liberado en la próxima versión. Solía ocurrir cuando las columnas declaradas, no correspondían con las visibles y el componente de la tabla, se perdía a la hora de inicializar los componentes definidos para cada campo.

**Comment by sandresmuniesa** [comment]
Buenos días.
Muchas gracias @xaabi6, con la solución de la función then ha desaparecido.

Respecto al segundo problema he probado a no ocultar la columna del id y sigue apareciendo. De todas formas, ¿hay algún commit en alguna rama con la solución? Probaría a añadirla al proyecto en local para poder seguir avanzando.

Un saludo.

**Comment by xaabi6** [comment]
Me alegra leer eso @sandresmuniesa.

Si la memoria no me falla, lo solucionamos en varios commits, pero si por el momento quieres seguir avanzando hasta que liberemos la nueva versión, podrías desactivar la inicialización de componentes y usar inputs normales y corrientes para que no te falle, eso sí, ten en cuenta que por la naturaleza de la edición en línea, lo que haya en el colModel, tiene que corresponder con lo declarado en las columnas de la tabla.

**Comment by sandresmuniesa** [comment]
Hola @xaabi6.

¿Hay una fecha estimada para la nueva versión?

Un saludo.

**Comment by xaabi6** [comment]
Por el momento no tenemos una fecha fijada @sandresmuniesa.

**Comment by xaabi6** [comment]
Acabamos de liberar la nueva versión @sandresmuniesa. Tenemos intención de sacar una versión 4.3.0 en las próximas semanas con todos los correctivos aplicados a la versión 5.0.0, de esta manera, podréis integrar los correctivos en vuestras aplicaciones sin tener que migrar a una versión mayor que tiene sus incompatibilidades con la rama 4.x.x.
