### ISSUE TITLE
Datatable multiorder

### ISSUE THREAD

**Issue by oierjim** [UDA-EJIE/udaRUP#187]
Hola 
Actualmente la datatable permite manteniendo el shift pulsado clicar en otra columna permitiendo multi ordenacion. El problema es que rup al hacer el filter no envia un multi sidx.

En el rup.table.request: Hemos sustituido la parte que rellena el elemento sidx y sord

if (data.order.length ==1) {
   sidx = data.columns[data.order[0].column].colSidx || data.columns[data.order[0].column].data;
   sord = data.order[0].dir;
}else if (data.order.length >1) {
   for (var i = 0; i<data.order.length; i++) {
      idx += data.columns[data.order[i].column].colSidx || data.columns[data.order[i].column].data;
      sord+= data.order[i].dir;
      if(i<data.order.length-1){
          sidx += ' ,';
	  sord += ' ,';
      }			
    }
}

y en el filter (rup.table.js)
 // var json = $.extend({}, data, tableRequest.getData()); comentar esta linea original
var json = tableRequest.getData();

Estaría meter algo asi para las nuevas versiones.

**Comment by xaabi6** [comment]
Aupa @oierjim, ya quedó añadido en la versión 5.0.2 que lanzamos hace casi un mes. El commit "[Mejora para poder ordenar por varios campos en las tablas](https://github.com/UDA-EJIE/udaRUP/commit/1afa94e4332c06e16a5783648f3927027f97155b)" fue el que incluyó esta funcionalidad.
