### ISSUE TITLE
Propiedad bStateSave de las rup_tqable

### ISSUE THREAD

**Issue by javarona75** [UDA-EJIE/udaRUP#189]
Buenas tardes.
Estoy trabajando en un proyecto con la versión 4.2 de UDA. El tema es que necesito guardar los parámetros de búsqueda de las rup_tables para cuando se vuelva a visitar la página que contiene cada rup_table (y volver a reponer los parámetros en los filtros de búsqueda).
Las DataTables parece que tienen un parámetro "bStateSave" que guarda en una cookie dichos parámetros de búsqueda en una cookie, pero no consigo que me funcione con las rup_table.
¿Hay alguna forma de guardar los parámetros del filtro de una rup_table en función de la URL o algo así, que permita reponer dichos parámetros cuando se vuelva a visitar la página?
Gracias y un saludo,
Jose

**Comment by xaabi6** [comment]
@javarona75, ¿conseguiste hacerlo funcionar?

**Comment by xaabi6** [comment]
Se cierra por inactividad y por haber proporcionado dos posibles soluciones.
