### ISSUE TITLE
[UDA] [Autocomplete] Problema combobox remoto

### ISSUE THREAD

**Issue by jalvarez1983** [UDA-EJIE/udaRUP#198]
Hola,

A raíz del commit 605bbf8 en las llamadas remotas se está sobrescribiendo el atributo label de cada item, lo que  deriva en errores.
Adjunto un gif con una prueba en la x21a (combobox remoto).

![autocomplete](https://user-images.githubusercontent.com/2207608/160639682-710de8fd-678c-4623-83c8-3c61b15e5e33.gif)

Muchas gracias

**Comment by xaabi6** [comment]
Corrección realizada, una vez más, gracias @jalvarez1983 👍

**Comment by jalvarez1983** [comment]
Por si sirve para alguien que ya tenga la versión 5.0.1 o 5.0.2 y le esté pasando lo mismo, lo hemos solucionado definiendo en el  sourceParam las propiedades (a parte del label y el value) .

![image](https://user-images.githubusercontent.com/2207608/160815964-9ab0112d-11c2-40d1-b10f-3172e771412c.png)
