### ISSUE TITLE
[rup_table.masterDetail] Detalle sin filtro. (v2.4.2)

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#2]
Nos está fallando al hacer un maestro detalle al utilizar el plugin “masterDetail” cuando en un detalle no usamos el plugin “filter”.  Intenta acceder a algún parámetro de la propiedad filter y falla.

De momento para solucionarlo hemos adoptado la siguiente solución:

**Fichero:** rup.table.masterDetail-2.4.2.js
**Líneas:** 91 - 98

**Actual:**
```javascript
	"jqGridSelectRow.rupTable.masterDetail": function(event, rowid, status){
		var lastRowid = $self.data("tmp.masterDetail.lastRowid");
		if (lastRowid === undefined || lastRowid!==rowid){
			$self.data("tmp.masterDetail.lastRowid", rowid);
			$self.rup_table("showSearchCriteria");
			$self.rup_table("filter");
		}
	},
```

Se está dando por hecho que tenemos un filtro y se está actualizando el “searchCriteria” y el “filter”.

**Propuesta:**
```javascript
	"jqGridSelectRow.rupTable.masterDetail": function(event, rowid, status){
		var lastRowid = $self.data("tmp.masterDetail.lastRowid");
			if (lastRowid === undefined || lastRowid!==rowid){
				if (jQuery.inArray("filter", settings.usePlugins) !== -1){
					$self.data("tmp.masterDetail.lastRowid", rowid);
					$self.rup_table("showSearchCriteria");
					$self.rup_table("filter");
				} else {
					$self.rup_table("reloadGrid");
				}
		}
	},
```

Aunque estamos utilizando la versión 2.4.2 en la versión 2.4.5 parece que no está cambiado.

**Comment by udaejie** [comment]
Hola, 

La solución ha sido probada y se considera correcta.
Se incluirá en la siguiente versión -v.2.4.6- de UDA.

Gracias, 

UDA
