### ISSUE TITLE
[report]Formato erróneo de números al generar informes excel

### ISSUE THREAD

**Issue by biremega** [UDA-EJIE/udaRUP#23]
Al generar informes en excel usando Rup-Report los campos numéricos no se formatean como tal.

He probado distintos formatos pero sin conseguir que se considere numerico en la hoja excel.

![sin titulo](https://cloud.githubusercontent.com/assets/17985389/19352638/d23c199e-9160-11e6-9983-c9db48012f95.jpg)

**Comment by biremega** [comment]
Lo mismo ocurre con las fechas.

**Comment by sergisu** [comment]
Hola, 

El componente rup.report no tiene en cuenta como se formatean los valores en las soluciones ofimáticas destino (excel, libreoffice, ...). 
Se trata de una exportación de datos genérica que tiene como base el csv donde no hay formato del dato sino simplemente una separación de valores por comas.

Si la solución ofimática que se usa en tu proyecto siempre es Excel, puedes modificar la generación del informe para formatear los datos usando poi o poi-ooxml, o para añadir cabeceras con negritas y cursivas o cabeceras anidadas, etcétera.
Pero UDA como conjunto de utilidades no se focaliza en una solución ofimática concreta.

Gracias por tus comentarios.

UDA
