### ISSUE TITLE
quita el atributo readonly a los campos que tenemos definidos en el colmodel

### ISSUE THREAD

**Issue by bilopavi** [UDA-EJIE/udaRUP#25]
en el fichero rup.table.formEdit-2.4.7.js función jqGridAddEditBeforeShowForm.rupTable.formEditing.readOnlyPks línea 519
1-settings.ownFormEdit debería ser settings.**formEdit**.ownFormEdit
2-la variable col**m**odel está definida como col**M**odel

**Comment by uGuinea** [comment]
Hemos confirmado el error, y tras probar el cambio, en la siguiente versión de uda (v 3.0.0) esté error estará corregido.

Gracias
