### ISSUE TITLE
Scroll en redimensión de pantalla

### ISSUE THREAD

**Issue by lapitzasclub** [UDA-EJIE/udaRUP#28]
En móvil cuando se realiza scroll a las pantallas **desaparece o aparece la barra de navegación**. La aplicación cuenta esta acción como una **redimiensión vertical** de la pantalla y hace que **el scroll se reinicie al principio del contenido.**
Se debería quitar el scroll en redimensión o en su defecto controlarlo únicamente a las redimensiones horizontales.

**Comment by xaabi6** [comment]
A día de hoy (19/02/2018), la versión que tenemos en la rama **develop** no sufre de este bug, por lo tanto, damos por finalizada la issue.
