### ISSUE TITLE
Asignar valor a rup_select remoto

### ISSUE THREAD

**Issue by JONAGUIPER** [UDA-EJIE/udaRUP#290]
Muy buenas,
Estamos intentando setear un valor a un combo que carga sus valores de manera remota, por lo que la opción .val(value) no funciona, y según la documentación de select2 hay que hacerlo asi:
https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2
Pero la cuestión es: esto no es compatible con la versión actual de rup_combo, además busco en la documentación y solo encuentro la información de la api y nada de ejemplos de uso... por lo que no sé si está implementado esto en el wrapper o extensión que hacen para crear el rup_select.

Gracias por la ayuda que puedan prestar

**Comment by hmartinez85** [comment]
buenas, si te he entendido bien, el la documentación de la API, puedes usar el setRupValue, la guía con más ejemplos la subiremos en breves.
Un saludo.

**Comment by JONAGUIPER** [comment]
no puedo usar eso porque el rup_select del tipo remoto y no carga los datos hasta que lo despliegas por primera vez.

**Comment by hmartinez85** [comment]
en ese caso sería la propiedad selected.
![image](https://user-images.githubusercontent.com/34453480/222720641-133a9ae9-7f15-45e5-9020-ca245886092b.png)

**Comment by JONAGUIPER** [comment]
de esa manera se carga el combo precargado y no es el caso de uso, explico:
es un formulario que se muestra vacío en primera instancia, luego el usuario introduce un dni y por ajax recupero la informacion de la persona y debo precargar los datos del formulario; en dicho formulario existen select para el lugar de residencia que se cargan vía NORA, en estos select  son en los que tengo el lio, ya que esos select que cargan sus opciones remotamente y en el momento que voy a setear el valor via javascript no lo hace porque la lista no está poblada...

Cuando voy a la documentación de select2 encuentro la información que coloqué en el primer mensaje... loque supone un sobre esfuerzo para realizar esa asignación... queria saber si este caso de uso esta planteado en la versión actual...

**Comment by hmartinez85** [comment]
Puedes poner capturas, para entenderlo mejor. gracias @JONAGUIPER

**Comment by JONAGUIPER** [comment]
estado inicial sin desplegar la lista la primera vez y seteando un valor que se que existira:
![image](https://user-images.githubusercontent.com/14790146/223041260-2f53c010-ea95-4a62-929e-40cb68154e95.png)
ni se inmunta.

Despliego la lista para que se carguen las opciones;
![image](https://user-images.githubusercontent.com/14790146/223041497-bbfa1897-c8ce-4de1-9633-6e171701df73.png)
Ejecuto el mismo comando:
![image](https://user-images.githubusercontent.com/14790146/223041619-6c75c8c3-9af6-4ba5-a7d5-acbf1cab096c.png)
lanzo los trigger, y nada:
![image](https://user-images.githubusercontent.com/14790146/223041812-291ddfeb-0835-4cda-94db-4d3b6090e3f7.png)
pero si graficamente seleciono ese apción una vez y cambio a otra si que lo setea;
![image](https://user-images.githubusercontent.com/14790146/223042005-5e96965d-63cb-4c2d-881b-1e42cd2bf9f7.png)
entiendo es por que se encuntra ahora la opcion aqui:
![image](https://user-images.githubusercontent.com/14790146/223042108-80104151-0907-4367-855d-a4ac933c9244.png)

Esto se lo muestro usando la consola ya que es lo mismo o parecido lo que uso via javascript.
La definicion del componente la hacemos asi:
![image](https://user-images.githubusercontent.com/14790146/223042483-32efea37-3dc3-4b13-b519-a9b02866d71d.png)

Espero que con esto me puedas entender

**Comment by hmartinez85** [comment]
Se cierra, añadiendo los serielizes correctos.
