### ISSUE TITLE
Rup_select devuelve string cuando es multiselect

### ISSUE THREAD

**Issue by JONAGUIPER** [UDA-EJIE/udaRUP#291]
Cuando un rup_select está configurado con la propiedad multiple a true, al hacer la invocación "getRupValue" cuando está seleccionado solo un valor de la lista, devuelve un string (o number) y no una matriz lo que origina una excepcion cuando  este campo está asociado a un modelo del tipo lista:
![image](https://user-images.githubusercontent.com/14790146/228768502-64410b5d-53d0-49dc-8373-b905fd6e8366.png)

he revisado el código y creo que el problema pudiera estar aquí:
![image](https://user-images.githubusercontent.com/14790146/228768823-ff351448-5849-4720-82ff-450e2fae9352.png)

para solventar mi problemática he extendido el método de la siguiente manera:
![image](https://user-images.githubusercontent.com/14790146/228769230-512ef60a-2880-4da5-b97e-ab08e062f822.png)

Espero les ayude a solventar este problema...

**Comment by marcos9818** [comment]
Aupa Jon Ander, ya se ha solucionado el problema y funciona correctamente, se subirá en la siguiente actualización.
