### ISSUE TITLE
La opción blank no aparece en el rup_select

### ISSUE THREAD

**Issue by JONAGUIPER** [UDA-EJIE/udaRUP#292]
Estoy inicializando un rup_select de la siguiente forma:
![image](https://user-images.githubusercontent.com/14790146/228770816-66547654-e49c-4a3b-8b93-38967b3f26f5.png)
dando como resultado:
![image](https://user-images.githubusercontent.com/14790146/228770932-84bd6cd0-ba38-44af-b560-9d22026a79b0.png)
por lo que la opción blank nunca aparece, para paliar este problema he colocado el "allowClear" para que aparezca una "x" muy pequeña para que pueda deseleccionar la lista:
![image](https://user-images.githubusercontent.com/14790146/228771488-ad4bdbd7-7db6-4d54-a3c1-514b0516b1ef.png)
pero según la documentación entiendo que debería aparecer una opción mas para que pueda ser seleccionada que es como si el componente estuviera vacío.

**Comment by marcos9818** [comment]
Aupa Jon Ander,

No se si esta puede ser una posible solución a tu problema, tener activado como bien has dicho el allowclear y también establecer un placeholder (El placeholder puede ser un String vacío, aunque en cualquier caso este siempre devolverá un String/Array vacío, dependiendo del tipo de select). 

Detallar que en el selectMultiple no se puede activar un allowClear, pero si no se selecciona ningún valor se activa el placeholder que actúa como una opción "blank".

Te adjunto una imagen con un ejemplo.

Un saludo.

![image](https://github.com/UDA-EJIE/udaRUP/assets/131156200/abea4f86-f36a-418b-a9e1-66fb649c9bc7)

**Comment by marcos9818** [comment]
Si esta solución no te funciona coméntame por favor los problemas que te surgen.

Un saludo y gracias.

**Comment by xaabi6** [comment]
Cerrada por inactividad.
