### ISSUE TITLE
Error interno del componente rup.select.js

### ISSUE THREAD

**Issue by sergeisg** [UDA-EJIE/udaRUP#299]
Buenos días.

En los rup_select con opción de autocomplete, a la hora de hacer una búsqueda, salta este feedback con un error undefined vacío.

![Screenshot_562](https://github.com/UDA-EJIE/udaRUP/assets/91953689/8cfb2e6d-4d58-4c52-86df-09bdba9f7ad3)

He localizado el error en [esta línea](https://github.com/UDA-EJIE/udaRUP/blob/e5ee342e98116c47bcd8bc80da4728a2b7ae9261/src/rup.select.js#L1154) del fichero rup.select.js

No se la razón exacta del fallo, pero el error viene a la hora de llamar al método blur(). 

No es la única vez que ocurre, pues después de realizar la búsqueda del autocomplete, salta también al seleccionar cualquiera de los resultados. Poniendo un punto de interrupción en la línea 4141 del select2.js y dandole a continuar, se puede completar la acción sin que salte el error. Sin embargo, a la hora de volver a hacer click en el select, salta el error inmediatamente. 

Esto también lo he apreciado en otro formulario, donde el mero hecho de hacer click en cualquier parte del formulario, ni siquiera en un input, activa el rup.validate.js que lanza este mismo feedback de error con undefined. 

A ver si nos podéis echar una mano con esto...

Gracias y un saludo.

**Comment by sergeisg** [comment]
Aupa Xabi. Pasa tanto en ad97a como en ae24a.

**Comment by xaabi6** [comment]
La ad97a la tengo montada, ¿cómo podría reproducir el error?

**Comment by sergeisg** [comment]
Tienes que ir al paso D de la solicitud. 
A la hora de loguearte con la app, dale a continuar en el cuadro de BakQ, luego escoges Certificados digitales y escoge el primero , NUEVOCIUD FICTICIO.
Una vez dentro, deberías estar en ad97aEutanasiaWar/inicio y debería salirte una solicitud en curso en Estado Borrador y C. Si le das a Continuar Solicitud, te lleva al paso D donde deberías de poder reproducir el error con el combo de Patología del paciente. Seguramente no se reproduzca visualmente porque recuerdo que se ocultó el feedback de ese error, pero debería reproducirse por detrás ya que simplemente se ocultaba.

**Comment by hmartinez85** [comment]
![imagen](https://github.com/UDA-EJIE/udaRUP/assets/34453480/1b189692-9139-49e1-a598-3329fb789843)
Hola, tengo que hacer algo más para reproducir el error, ahora no logro que me salga

**Comment by hmartinez85** [comment]
he probado y me funciona mal, solo falla cuando tarda en traer los datos, y vuelvo a tocar el select que no debería dejar
es decir , llamo para traer los datos, mientras los carga, toco otro select y vuelvo a tocar el mismo, y como hace la misma llamada el componente lanza un error, por doble llamada,
, es ese el error?

**Comment by hmartinez85** [comment]
#ac7ada0a130a9386bfeb28f923d12bbee3b33655

**Comment by hmartinez85** [comment]
https://github.com/UDA-EJIE/udaRUP/commit/ac7ada0a130a9386bfeb28f923d12bbee3b33655
