### ISSUE TITLE
Problem with rup_date with the same id

### ISSUE THREAD

**Issue by gorkazar7** [UDA-EJIE/udaRUP#3]
Intento resumir mi problema:

El caso es que yo incluia 2 jsps (jsp:unclude) dentro de mi detalle. 
El resultado final era algo parecido a esto (por resumir)

<div id="contrato_compra">
                <input id="fecEntContrato"/>
</div>

<div id="contrato_alquiler">
                <input id="fecEntContrato"/>
</div>

Despues al convertir esos input en rup_date utilizaba algo del estilo.

      $('#contrato_compra #fecEntContrato).rup_date ({});
      $('#contrato_ alquiler #fecEntContrato).rup_date ({}); 

El selector de jquery es correcto pero no me creaba el rup_date. Al final depurando el rup_date y tras volverme un poco loco me he dado cuenta de que no estan creando bien los rup_date. 

Un saludo

**Comment by udaejie** [comment]
Hola, 

A día de hoy, la implementación del componente RUP Date así como del widget Datepicker de jqueryUI no permiten la inicialización de varios componentes con el mismo id a pesar de que el selector con el que se estén referenciando sea único. 

Esto se debe a que internamente utilizan el valor del atributo id del elemento del DOM sin tener en cuenta el selector con el que se ha invocado. El uso del mismo id en distintos componentes produce errores porque no es capar de invocar inequívocamente a cada elemento.

De todos modos de acuerdo a las reglas de validación del W3C los identificadores de los elementos de una página HTML deben de ser únicos en todo el documento, por lo que lo ideal sería que dicho identificador fuese dinámico para evitar problemas de este tipo.

Saludos,

UDA
