### ISSUE TITLE
Error con el overlay del menú

### ISSUE THREAD

**Issue by lapitzasclub** [UDA-EJIE/udaRUP#30]
**En dispositivos móviles o resoluciones bajas**, al desplegar el **rup_navbar** se muestra un overlay oscuro entre el menú y el contenido principal. La salida de este overlay está sujeta únicamente a pulsación del botón de despliegue de menú, con lo que si se hace click para desplegar el menú y antes de desplegarse se vuelve a hacer click el **menú queda desplegado pero sin el overlay**.
A partir de este momento el funcionamiento de salida del overlay con el menú es el inverso al normal a no ser que se repita la misma acción.

**Comment by xaabi6** [comment]
A día de hoy (19/02/2018), la versión que tenemos en la rama **develop** no sufre de este bug, por lo tanto, damos por finalizada la issue.
