### ISSUE TITLE
[rup_upload] botón "Abrir" no funciona en I.E.

### ISSUE THREAD

**Issue by jorgeb51** [UDA-EJIE/udaRUP#38]
Este botón (es un elemento "button") se está envolviendo en un tag “a”. Parece que esta solución no funciona en I.E.
![image](https://cloud.githubusercontent.com/assets/8099641/25955477/aebffebe-3669-11e7-8b80-a000385cfa18.png)
He visto que la template encargada de pintar esto se encuentra en: rup.js - línea 95717
`    + "</span></span>\r\n\r\n\r\n        </div>\r\n        <div class=\"col-xs-6 col-md-4 fileupload-buttonbar\">\r\n              <a href=\""
    + alias4(((helper = (helper = helpers.url || (depth0 != null ? depth0.url : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"url","hash":{},"data":data}) : helper)))
    + "\">\r\n                <button type=\"button\" class=\"btn btn-primary download\">\r\n                    <i class=\"fa fa-download\" aria-hidden=\"true\"></i>\r\n                    <span>Abrir</span>\r\n                </button>\r\n              </a>\r\n\r\n                <button type=\"button\" class=\"btn btn-secondary delete\" data-type=\""
 `

**Comment by jorgeb51** [comment]
Una posible solución es modificar la plantilla [rup.upload.downloadTemplate.hbs](https://github.com/UDA-EJIE/udaRUP/blob/master/src/templates/rup.upload.downloadTemplate.hbs) con el cambio:
`<a href="{{url}}">
                <button type="button" class="btn btn-primary download">
                    <i class="fa fa-download" aria-hidden="true"></i>
                    <span>Abrir</span>
                </button>
              </a>`
por:
`
<a href="{{url}}" class="btn btn-primary download">
                    <i class="fa fa-download" aria-hidden="true"></i>
                    <span>Abrir</span>
              </a>
`

**Comment by uGuinea** [comment]
Corregido para la próxima versión UDA 3.1
Hemos optado por una solución similar a la propuesta, gracias por el reporte.
