### ISSUE TITLE
rup_table multiselect

### ISSUE THREAD

**Issue by gorkazar7** [UDA-EJIE/udaRUP#4]
Buenas,

Estoy teniendo un problema con el multiselect. Me explico.

Siempre compruebo la seleccion con 
$("#Viviendas").rup_table("getSelectedIds").selectedIds

Cuando selecciono todo ok
Si selecciono 2 también.

Después selecciono todos. El selector me sale vació aunque el selectedAll me da true

No existe alguna forma de saber todos los ids seleccionados?

**Comment by udaejie** [comment]
Hola, 

El componente multiselección del componente RUP Table funciona del siguiente modo:

•	El comportamiento normal, según se carga la pantalla y se inicializa el componente, es devolver los identificadores de los registros seleccionados en el objeto que devuelve el método getSelectedIds tal y como indicas.
•	Cuando se seleccionan todos los elementos se activa el flag selectedAll y el componente RUP Table se comporta en modo “selección inversa”. Es decir, se devuelven los identificadores de los registros deseleccionados en lugar de los seleccionados.

Este último comportamiento se definió por el modo en el que obtiene los datos de los registros el componente RUP Table. Al acceder a la pantalla de la aplicación que contiene una tabla se recuperan solo los registros que se muestran en la página inicial. El número de elementos por defecto es de 10 pero es personalizable (20,30,50…). Sin embargo, solo se puede conocer de antemano los identificadores de los registros que se van visualizando en la tabla. El objetivo de esto es no recuperar del servidor más información de la que se va a visualizar agilizando la navegación y reduciendo el consumo de datos.

Teniendo en cuenta esto, se observa que según vamos seleccionando registros de entre las páginas de la tabla por las que navegamos no hay problema a la hora de obtener los identificadores de cada registro. Sin embargo, si estamos trabajando en modo “selección inversa” no podemos conocer los identificadores de los registros más allá de las páginas por las que se ha navegado. Este es el motivo por el que se parte de una selección de todos los elementos de la tabla e ir anotando los deseleccionados.

En caso de necesitar obtener los identificadores de los elementos seleccionados se debería de realizar una consulta al servidor de aplicaciones para que devuelva los identificadores de los registros que cumplen los criterios de filtrado actuales y no han sido deseleccionados.

Un saludo, 

UDA
