### ISSUE TITLE
El componente rup_combo no funciona correctamente

### ISSUE THREAD

**Issue by lapitzasclub** [UDA-EJIE/udaRUP#42]
La mayoría de problemas están relacionados con la opción seleccionada, se puede reproducir en:

http://www.ejie.eus/x21aAppWar/patrones/comboEnlazadoSimple

Tiende a mostrar como seleccionado el primer elemento del source aunque cualquier otro esté seleccionado...
Aparte en los combos enlazados, al cambiar el parent de valor, el hijo recarga tomando el parent como referencia pero vuelve a marcar el valor que tenía seleccionado anteriormente entre los valores del nuevo source.

**Comment by sergisu** [comment]
Fix #42
