### ISSUE TITLE
Algunas plantillas de Handlebars no cumplen i18n

### ISSUE THREAD

**Issue by jorgeb51** [UDA-EJIE/udaRUP#43]
Actualmente varias de las plantillas hbs que introducen palabras no internacionalizadas ([rup.upload.downloadTemplate.hbs](https://github.com/UDA-EJIE/udaRUP/blob/master/src/templates/rup.upload.downloadTemplate.hbs), [rup.upload.uploadTemplate.hbs](https://github.com/UDA-EJIE/udaRUP/blob/master/src/templates/rup.upload.uploadTemplate.hbs), [rup.widget.search.hbs](https://github.com/UDA-EJIE/udaRUP/blob/master/src/templates/rup.widget.search.hbs), ...)

Una posible solución, es adaptar el helper de i18n ([handlebars-helper-i18n.js](https://github.com/UDA-EJIE/udaRUP/blob/master/src/helper/handlebars-helper-i18n.js)) para que pueda recuperar literales de los ficheros json de RUP:

```
Handlebars.registerHelper('i18n', function (key, options) {
    options = options || {};
    options.hash = options.hash || {};	
	bundle = options.hash.bundle || 'app';//por defecto literales de app (si se indica la palabra 'base' utilizará literales de rup)
	
	
    var language;

    if (typeof key !== "string") {
      throw "{{i18n}} helper: invalid key. Object keys must be formatted as strings.";
    }

    if (typeof options.hash.language === "string") {
      language = options.hash.language;
    } else {
      language = this.datosIdioma;
    }

      //return options.data.languages[language][key];
	  //return $.rup.i18nParse($.rup.i18n.app, key);
      return $.rup.i18nParse($.rup.i18n[bundle], key);
  });
```

Y en las plantillas sustituir los mensajes no internacionalizados por variables i18n que apunten a los literales de los componentes en los ficheros rup.
Por ejemplo ([rup.upload.downloadTemplate.hbs](https://github.com/UDA-EJIE/udaRUP/blob/master/src/templates/rup.upload.downloadTemplate.hbs)):
`<span>Abrir</span>` por: `<span>{{i18n "rup_upload.openUploaded" bundle="base"}}</span>`

**Comment by uGuinea** [comment]
En la versión UDA 3.1 vamos a sacar una corrección para este error.

Similar a tu respuesta, hemos optado por retornar en el helper:

`return $.rup.i18nParse($.rup.i18n.base, key);`

De tal modo que en las plantillas no hace falta parametrizar el bundle
`<span>{{i18n "rup_upload.openUploaded"}}</span>`

Gracias por el reporte
