### ISSUE TITLE
[rup_table] En IE 9, no se está mostrando el icono del registro seleccionado, en una tabla con multi selección.

### ISSUE THREAD

**Issue by pjpena** [UDA-EJIE/udaRUP#45]
En una aplicación UDA 3 con IE9, al selecionar un registro en una tabla con multiselección, no aparece el icono del lápiz (registro activo) junto a la primera celda del registro seleccionado.

![snap 2017-05-18 at 16 26 48](https://cloud.githubusercontent.com/assets/23494678/26207115/ec3cb1a6-3be6-11e7-9a1f-4affcceed3cd.png)

En FF y Chrome dicho icono se muestra correctamente.

![snap 2017-05-18 at 16 28 14](https://cloud.githubusercontent.com/assets/23494678/26207152/0552629e-3be7-11e7-8a8e-545dfc45b66e.png)

Probado en la x21a: http://www.ejie.eus/x21aAppWar/table/formEditMultiselection

**Comment by uGuinea** [comment]
Solucionado en la release 3.1.0
