### ISSUE TITLE
[rup_feedback][rup_validate] No se oculta bien el feedback

### ISSUE THREAD

**Issue by lapitzasclub** [UDA-EJIE/udaRUP#47]
El método 'hide' de rup_feedback no funciona correctamente, y debe ser al que llama el método 'resetForm' de rup_validate, puesto que el resultado es el mismo.

Debería ocultarse completamente el feedback o el rup_validate invocar al método 'close' que sí lo cierra correctamente...

**Comment by uGuinea** [comment]
Ya se solucionó en la release 3.1.0
