### ISSUE TITLE
rup_table : Sobrescribir acción guardado 

### ISSUE THREAD

**Issue by biremega** [UDA-EJIE/udaRUP#5]
Se ha eliminado de la nueva versión la funcionalidad de sobrescribir la acción de guardar en los formularios detalle.

En versiones antiguas de UDA podíamos hacerlo de la siguiente forma:
```
($("#detailBody").rup_dialog("getOption", "buttons"))[0].click = function() {
$("#seguimientodiario").rup_maint("saveMaint", null, null, aftersavefunc, null);
};
```

En la versión actual, esto no es soportado, en cambio tenemos eventos que se ejecutan antes del guardado pero estos no previenen el guardado. (_jqGridAddEditBeforeCheckValues, jqGridAddEditBeforeSubmit_)

Un caso útil que necesita de esto: Ejecutar un PLSQL antes del guardado que en función de la respuesta se añada o no.

**Comment by udaejie** [comment]
Hola, 

A partir de la versión v2.4.0 de UDA se introdujo el nuevo componente RUP Table que sustituye a los obsoletos Grid y Maint. 

A la hora de diseñar e implementar el nuevo componente se introdujeron modificaciones por lo que muchas estructuras internas han cambiado y no son accesibles como eran en los componentes antiguos.

El modo en el que queréis reemplazar el evento `click` en el botón `Aceptar `del formulario de detalle podría realizarse con el nuevo componente referenciando los nuevos elementos y utilizando la nueva API, pero no es recomendable hacerlo de este modo.

El evento `jqGridAddEditBeforeSubmit `que indicáis permite la ejecución de una función asociada al evento antes del guardado de la edición o inserción que se esté realizando. Además permite detener la operación mediante el parámetro que se devuelve. Atención en el tipo del parámetro, ya que debe de ser un array en el cual, el primer parámetro será un boolean que indica si debe continuar el guardado o no.

Un ejemplo sería el siguiente:

```
       $("#table").on("jqGridAddEditBeforeSubmit", function(){
             // Ejecucion del proceso 
             var ret = proceso();
             
             // Devuelve true o false para continuar con la ejecución del guardado
             return [ret];
       });
```


Atendiendo al caso útil que proponéis: 

_Ejecutar un PLSQL antes del guardado que en función de la respuesta se añada o no._

Sería más correcto que la ejecución de ese PLSQL que determina si se debe realizar el guardado o no, se realice en el propio servicio que realiza el _insert _del elemento de la tabla. La ejecución sería previa a la llamada al método del _Dao _que realiza la inserción y dependiendo del valor de la respuesta se ejecutaría el guardado o no. En caso de no realizarse se gestionaría en mensaje de retorno mediante excepciones como si se tratase de una validación de negocio.

Implementándolo de este modo se mejoraría el tiempo de respuesta y se realizaría dentro de una misma transacción.

En caso de desarrollarlo dentro de la función del evento (no recomendable), la llamada Ajax utilizada para ejecutar el PLSQL debería de ser síncrona ya que necesitamos saber la respuesta para determinar si se debe realizar el guardado o no.

UDA
