### ISSUE TITLE
[rup_table] Problema con el autocomplete del multifilter

### ISSUE THREAD

**Issue by pjpena** [UDA-EJIE/udaRUP#50]
A la hora de recuperar los filtros almacenados por el usuario, éstos se pintan por debajo de la capa, lo cuál no permite seleccionar ninguno de ellos.

![snap 2017-05-24 at 08 28 45](https://cloud.githubusercontent.com/assets/23494678/26389605/0cc47e0e-405b-11e7-9810-42200ecdb4fe.png)

Inspeccionando el DOM del documento, hemos visto que a la capa que "bloquea" el formulario cuando se abre el diálogo del multifilter se le aplica un z-index: 100 

![snap 2017-05-24 at 08 38 44](https://cloud.githubusercontent.com/assets/23494678/26389899/7226332c-405c-11e7-841a-2426e29a24f9.png)

Y al diálogo que contiene el autocomplete se le asigna un z-index: 101

![snap 2017-05-24 at 08 33 44](https://cloud.githubusercontent.com/assets/23494678/26389748/c0dc0f7e-405b-11e7-9351-1d8d42ac060c.png)

Sin embargo, al elemento `<ul>` $("#xxx_multifilter_combo_menu") que contiene los resultados de la búsqueda, no se le está aplicando z-index alguno, por lo que se pintan por debajo de la capa que bloquea el díalogo y no se permite seleccionar.

![snap 2017-05-24 at 08 48 31](https://cloud.githubusercontent.com/assets/23494678/26390198/d03526b6-405d-11e7-8723-b13b73dd41f3.png)

La solución pasaría por asignarle a ese elemento un z-index superior a 101, para que se pueda seleccionar en la interfaz.

Se ha reproducido tanto en UDA 2.4.X como en UDA 3.X

**Comment by enekoza** [comment]
Se ha corregido el comportamiento del desplegable del menú de selección del filtro para que se muestre siempre por encima del diálogo de selección.
