### ISSUE TITLE
[rup_wizard] gestión de componentes accordion

### ISSUE THREAD

**Issue by jorgeb51** [UDA-EJIE/udaRUP#54]
En el componente wizard, al generar el paso resumen se están duplicando los iconos de las cabeceras de los acordeones:
![image](https://cloud.githubusercontent.com/assets/8099641/26485816/bbfb60a6-41f8-11e7-860d-49031ae12a28.png)

El problema es que cuando el wizard resetea los acordeones, no borra el span que contiene el icono de la cabecera. De forma que cuando vuelve a generar el componente, lo duplica.
Hemos visto que se soluciona añadiendo una línea al siguiente código del [rup.wizard.js](https://github.com/UDA-EJIE/udaRUP/blob/master/src/rup.wizard.js) (línea 565):

 ```
            //Gestionar componentes RUP
            //rup_accordion
            $("#step" + stepNumber + " .ui-accordion").each(function () {
                $(this).attr("id", $(this).attr("id") + "_summary");
                $(this).removeAttr("class");
                $(this).children("h1").removeAttr("class");
                //XXX Se elimina el icono anterior para que no se duplique
                $(this).children("h1").children("span.ui-icon").first().remove();
                $(this).children("div").removeAttr("class");
                if ($.isEmptyObject(settings.rupAccordion)) {
                    $(this).rup_accordion(settings.accordion);
                } else {
                    $(this).rup_accordion(settings.rupAccordion);
                }
            });
```

Un saludo,

**Comment by enekoza** [comment]
Se aplica la solución propuesta para solucionar el problema.
