### ISSUE TITLE
[rup_validate] Validacion de numero decimal (number:true)

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#57]
Estoy intentando probar la validación de numero decimal con el componente rup_validate y parece que no lo esta validando bien. No admite, ni decimales con coma ni con punto, ni siquiera números enteros sin decimales.
Lo estoy probando en la aplicación de ejemplo:
http://www.ejie.eus/x21aAppWar/patrones/validateRules

Parece que la expresión regular contra la que lo valida no es correcta.

Un saludo

**Comment by uGuinea** [comment]
Error solo reproducible en uda 3.1.0, en esta versión de forma fortuita se cambió la expresión regular de los decimales en los ficheros i18n de uda (rup.18n_xx.json)

`
"regexp": {
      "decimal": "^-?(?:d+|d{1,3}(?:.d{3})+)(?:,d+)?$"
    }
`

Debería ser 

`
"regexp": {
     "decimal":"^-?(?:\\d+|\\d{1,3}(?:.\\d{3})+)(?:\\,\\d+)?$"
    }
`
