### ISSUE TITLE
Instalación Neon y weblogic 10.3.6

### ISSUE THREAD

**Issue by AmandaL89** [UDA-EJIE/udaRUP#58]
Hola,
Me estoy instalando el eclipse Neon version3.1.0 siguiendo vuestras instrucciones pero me da error. Si en el eclipse.ini cambio la vm por la de jrockit del weblogic 10.3.6, el eclipse no arranca. Si dejo la que tiene, que es java 1.8 si me arranca pero a la hora de configurar el servidor no me reconoce el weblogic. Al darle a start al servidor es como si no encontrara la ruta y el classpath en console me parece vacio.
¿Que estoy haciendo mal? 
Tengo el helios uda con weblogic 10.3.5 y no he tenido ningun problema. Siguiendo las instrucciones me ha funcionado.
Espero vuestra respuesta.

Un saludo y gracias

**Comment by sergisu** [comment]
Hola, 

La instalación de Eclipse Neon requiere un entorno Java 1.7 o superior. Este es el motivo del error al tratar de iniciarlo con la máquina virtual del weblogic 10.3.6, que es java 1.6.

La configuración de arranque que aparece en el Eclipse Neon de los descargables de UDA es [UNIDAD_INSTALACION]:/Program Files/Java/jdk1.8.0_45/bin
Podría ser esta u otra versión superior.

Una vez arrancado el eclipse, en la configuración del servidor Oracle Weblogic Server 11g(10.3.6), se selecciona el directorio de instalación del servidor ( [UNIDAD_INSTALACION]:\bea\weblogic1036\wlserver_10.3) y automáticamente detecta el Java Home a utilizar, por defecto, [UNIDAD_INSTALACION]:\bea\java\jrockit-jdk1.6.0_45-R28.2.7-4.1.0

Prueba a configurar de nuevo el servidor.

Saludos.
