### ISSUE TITLE
rup_autocomplete : combobox + validate. Versión 2.4.5

### ISSUE THREAD

**Issue by gorkazar7** [UDA-EJIE/udaRUP#6]
Buenas, tenemos algunos problemas con el autocomplete con combobox:true

Versión 2.4.5

- Por un lado al abrir un detalle de un registro con un autocomplete. Si pulsas sobre el autocomplete y luego pinchas fuera, este se vacía
- Si le pones una validación en el rup_table, el icono aparece detrás del botón de desplegar
- Para conseguir la validación, tenemos que poner el mismo id al input y al label. Al hacer esto ahora perdemos la funcionalidad de que al pulsar sobre el label el foco vaya al input.

Saludos

**Comment by enekoza** [comment]
Las modificaciones introducidas solucionan el problema del siguiente modo:

- La modificación de la hoja de estilos del autocomplete posiciona correctamente el icono de validación después del botón de desplegar.
- Se ha modificado la gestión del componente RUP Validate. Se tiene en cuenta el componente Autocomplete para obtener correctamente el label con el que se identificará el campo validado. 

En el HTML sería:
```
<label for="rol_filter_table" class="formulario_linea_label">Rol:</label>
<input type="text" name="rol" class="formulario_linea_input" id="rol_filter_table" />
```

Mientras que en el js de inicialización dentro de una tabla:

```
search:{
    validate:{
        rules:{
    	    "rol":{required:true}
    	}
   }
},

```
- Respecto al problema con el autocomplete en un detalle de un registro, la modificación en el método setRupValue ha resuelto el problema.
