### ISSUE TITLE
[rup_table] i18n de botones del formulario de alta

### ISSUE THREAD

**Issue by uGuinea** [UDA-EJIE/udaRUP#60]
Los botones que genera de forma automática el rup_table para los formularios de alta/edición no tienen literales asociados; solo aparece cancel, save y saveAndContinue.

**Comment by enekoza** [comment]
Se ha comprobado que no era un problema en la generación de una aplicación a partir del plugin de UDA.

El problema era que los literales faltaban en los ficheros de resources de Spring del war x21aAppWar de la aplicación de ejemplo udaDemoApp.
