### ISSUE TITLE
boton x del detalle no se visualiza

### ISSUE THREAD

**Issue by gorkazar7** [UDA-EJIE/udaRUP#63]
En la version 3.1.0 no se visualiza el boton x del detalle. He comprobado la version 3.0.1 y funciona correctamente, pero en la 3.1.0 no. He visto que en la version 3.1.0 no llama a la funcion .button en la linea 48481 del rup.js

		this.uiDialogTitlebarClose = $( "<button type='button'></button>" )
			.button( {
				label: $( "<a>" ).text( this.options.closeText ).html(),
				icon: "ui-icon-closethick",
				showLabel: false
			} )
			.appendTo( this.uiDialogTitlebar );

No se muy bien el porque esta vez, igual vosotros lo veis más rapido

Saludos

**Comment by jorgeb51** [comment]
A nosotros nos pasaba lo mismo. En nuestro caso vimos que en el _layoutLoader.js nos faltaba esta línea:
```
// Evitar conflictos entre Bootstrap y jQueryUI
$.fn.bootstrapBtn = $.fn.button.noConflict();
```

**Comment by ihernaez** [comment]
Esa linea no debería ser parte de RUP? Para facilitar la migración entre versiones sin tener que tocar el código de la aplicación... no es que sea parte del layout precisamente...

Se podría incluir algo así en rup_button (p.e.) sin romper nada en las aplicaciones:

if (typeof $.fn.bootstrapBtn === 'undefined' && typeof $.fn.button.noConflict !== 'undefined') {
    $.fn.bootstrapBtn = $.fn.button.noConflict();
    // Para evitar que kasken las aplicaciones ya migradas
    if (typeof $.fn.button.noConflict === 'undefined') {
        $.fn.button.noConflict = function() {
            return $.fn.bootstrapBtn;
        };
    }
}
