### ISSUE TITLE
combo dentro de rup_table edición inline

### ISSUE THREAD

**Issue by gorkazar7** [UDA-EJIE/udaRUP#64]
Buenas,

Estabamos intentando usar un combo o un autocomplete dentro de un rup:table edición inline. Con el autocomplete hemos desistido y viendo el código que teneis dentro de x21app para meter un combo algo hemos conseguido.  Este era el código que he visto que teniais (estaba comentado eso si)

			{ name: "rol", index: "rol", editable:true, width: 140,
				rupType: "combo",
				rwdClasses:"hidden-xs hidden-sm hidden-md",
				editoptions: {
					source : [
					   {label: "---", value:""},
					   {label: $.rup.i18n.app["GRID_simple##rol"]["administrador"], value:"administrador"},
					   {label: $.rup.i18n.app["GRID_simple##rol"]["desarrollador"], value:"desarrollador"},
					   {label: $.rup.i18n.app["GRID_simple##rol"]["espectador"], value:"espectador"},
					   {label: $.rup.i18n.app["GRID_simple##rol"]["informador"], value:"informador"},
					   {label: $.rup.i18n.app["GRID_simple##rol"]["manager"], value:"manager"}
					]
				}
				, formoptions:{rowpos:3, colpos:2}
			}

Nuestro problema es que al querer formar un combo no sabemos muy bien como especificar el label y el value. Os pongo un ejemplo sencillo (he quitado lo que no vale)

                        {   name: "desTipoSubsanacionCas", 
                            align: "", 
                            width: 140, 
                            editable: true, 
                            rupType: "combo",
            				editoptions: {
            					source : $.m62ab.combos.tipoSubsanacion,
                            	                 valueName: "codTipoSubsanacion",    
                            	                  labelName: "desTipoSubsanacionCas", 
            				}
                        }

El problema es que de esa manera el combo sale bien, pero logicamente al modificar el combo nos envia el codTipoSubsanación, dentro del campo desTipoSubsanacionCas.

Si lo metemos de esta manera

                        {   name: "codTipoSubsanacion", 
                            align: "", 
                            width: 140, 
                            editable: true, 
                            rupType: "combo",
            				editoptions: {
            					source : $.m62ab.combos.tipoSubsanacion,
                            	                 valueName: "codTipoSubsanacion",    
                            	                  labelName: "desTipoSubsanacionCas", 
            				}
                        }

Lo que nos muestra en la tabla es el codigo, con lo cual tampoco nos vale. Al darle a editar  ya se ve la descripcion y al enviar envia el código.

Hay algo parecido??

Como os he dicho prefiririamos con el autocomplete, pero de momento hemos desistido

Saludos

**Comment by enekoza** [comment]
En la configuración del combo para la columna `codTipoSubsanacion` asignáis a la propiedad `source` el valor de `$.m62ab.combos.tipoSubsanacion`.

¿El valor se corresponde con un array de objetos json? ¿o es un string con una url para obtener los valores mediante una petición XHR?

De todos modos las propiedades `valueName` y `labelName` son propias del componente RUP Autocomplete. No veo como pueden estar actuando sobre el comportamiento del combo.

**Comment by gorkazar7** [comment]
El valor es un array de objetos json que recuperamos previamente de BD. 

Y entonces como podríamos usar un combo en un rup_table, con edición in_line? 

saludos y gracias por responder

**Comment by enekoza** [comment]
El ese caso, el combo se inicializa a partir de un origen de datos local por lo que los objetos del array deben de estar formados con las propiedades `label` y `value`.

La transformación se podría realizar del siguiente modo.

```js
$.map($.m62ab.combos.tipoSubsanacion, function(elem){
	return {
		label: elem.desTipoSubsanacionCas,
		value: elem.codTipoSubsanacion
	}
});
```
Por otro lado para que realice correctamente la gestión de los datos entre el combo y el valor de la columna de la tabla se deberá de utilizar el formater `rup_combo`.

Un ejemplo de una configuración válida sería:

```js
{ name: "codTipoSubsanacion", 
	rupType: "combo",
	formatter: "rup_combo",
	editoptions: {
		source: $.map($.m62ab.combos.tipoSubsanacion, function(elem){
			return {
				label: elem.desTipoSubsanacionCas,
				value: elem.codTipoSubsanacion
			}
		}),
	}
},
```
Se va a revisar el uso del autocomplete dentro de la tabla en modo edición inline para ver si existen problemas.

**Comment by enekoza** [comment]
Se ha solventado el uso del autocomplete dentro de una tabla de edición en línea en la versión v3.2 de UDA.

Su uso sería similar al indicado para el combo:

```js
{ name: "codTipoSubsanacion", 
	rupType: "autocomplete",
	formatter: "rup_autocomplete",
	editoptions: {
		source: $.map($.m62ab.combos.tipoSubsanacion, function(elem){
			return {
				label: elem.desTipoSubsanacionCas,
				value: elem.codTipoSubsanacion
			}
		}),
	}
},
```

**Comment by gorkazar7** [comment]
existe alguna forma de arreglarlo en la 3.1.0??

saludos y gracias
