### ISSUE TITLE
[rup_table] v3.1 ORDER_BY_WHITE_LIST

### ISSUE THREAD

**Issue by gorkazar7** [UDA-EJIE/udaRUP#67]
Buenas,

Yo creo que es un issue pero vosotros direis.

al generar codigo de una BD cuyo id por ejemplo es ID_USUARIO, se crea el mantenimiento y a la variable de ordenacion del rup_table se pone a filtrar por el campo del modelo idUsuario. 

					primaryKey: "idUsuario",
					sortname: "idUsuario",

Esto es correcto desde mi punto de vista. La js no tiene porque saber cual es el campo de BD a filtrar.

Pero el problema viene al hacer la ordenacion

if (jqGridRequestDto != null) {
                    query = JQGridManager.getPaginationQuery(jqGridRequestDto, query, LibroDaoImpl.ORDER_BY_WHITE_LIST);
             }

La variable ORDER_BY_WHITE_LIST contiene un array con ID_USUARIO y da un error. No me he metido a ver cual es el código de getPaginationQuery pero entiendo que en algun sitio se deberia hacer la conversion de idUsuario a ID_USUARIO

De momento con poner en el rup_table lo siguiente funciona, pero entendemos que no es lo correcto

					primaryKey: "ID_USUARIO",
					sortname: "ID_USUARIO",

Saludos

**Comment by enekoza** [comment]
Se han modificado las plantillas de generación de código para que los campos de la white list se generen a partir de los alias correspondientes.

De este modo la ordenación se realiza de acuerdo al nombre de la propiedad del bean.
