### ISSUE TITLE
rup_autocomplete 2.4.6

### ISSUE THREAD

**Issue by gorkazar7** [UDA-EJIE/udaRUP#7]
Estoy intentado crear un autocomplete con disabled:true y no es posible. El problema yo creo que es que en la inicializacion del componente ejecutáis la deshabilitacion de este antes de cargarlo.

Esta funcion de deshabilitar deberia ir detras de la modificacion de identificadores creo yo

Saludos

					// Modificar identificadores
					settings.loadObjects = settings.id+"_label";
					$("#"+settings.id).attr("id", settings.id+"_label");
					$("#"+settings.id+"_value").attr("id", settings.id);

			//Deshabilitar
					if (settings.disabled===true) { $("#"+settings.id).rup_autocomplete("disable");
						if (settings.combobox)
							$('span').has('#'+settings.id+'_label').find("a").attr("style","display:none");

					}else if (settings.disabled===false){ //habilitar
						$("#"+settings.id).rup_autocomplete("enable");
						if (settings.combobox){
							$('span').has('#'+settings.id+'_label').find("a").removeAttr("style");
						}
					}

**Comment by enekoza** [comment]
Se ha corregido el siguiente error:

El componente no se inicializa deshabilitado en caso de que se incluya en la configuración inicial la propiedad `disabled: true` 

Se ha modificado la implementación de los métodos enable y disable del componente para mejorar la gestión de las acciones correspondientes.

Para la resolución del problema se ha modificado el método _init de modo que se gestiona correctamente el estado del componente a la hora de inicializarse.

La corrección se ha realizado mediante el commit  UDA-EJIE/udaDemoApp@128b02a
