### ISSUE TITLE
Al validar campos rup_date y rup_autocomplete, no se visualiza correctamente el error 

### ISSUE THREAD

**Issue by bilopavi** [UDA-EJIE/udaRUP#70]
Buenas,
Al validar campos rup_date y rup_autcomplete, no se visualiza correctamente el error
No captura el label asociado al input(en el caso del autocomplete se valida el campo '_label'), por lo que en la lista de errores, aparece el texto 'undefined' como etiqueta del campo.
Tampoco se añade correctamente los mensajes/iconos de error en los campos validados
Que no valide campos deshabilitados, ¿es un comportamiento esperado? he probado con un campo rup_date y otro rup_combo

En la primera imagen, se ve que no captura los textos de label asociados a los campos de formulario y que no valida el rup_combo por estar deshabilitado

![captura](https://user-images.githubusercontent.com/15363919/31755985-aee51ab2-b4a1-11e7-9ca9-39ff835531c7.JPG)

En la segunda imagen se ve como si valida el campo rup_combo al estar habilitado

![captura2](https://user-images.githubusercontent.com/15363919/31756017-ded49284-b4a1-11e7-8cbf-c5091fdd6411.JPG)

Un saludo

**Comment by hmartinez85** [comment]
Buenas tardes,

La parte donde no se está validando el rup_combo tengo una duda, he realizado varias pruebas deshabilitando el rup_combo:
Ej: 
```js
$("#rol_detail_table").rup_combo("disable");
```
![image](https://user-images.githubusercontent.com/34453480/34774901-82ffd228-f611-11e7-9601-d09fdebe5a60.png)

y no consigo reproducir el error, como se está deshabilitando el combo?, por si fuera por eso.

Gracias.
