### ISSUE TITLE
Emulación XHR en RUP Upload

### ISSUE THREAD

**Issue by enekoza** [UDA-EJIE/udaRUP#77]
Se ha comprobado que la gestión de las peticiones de subida de ficheros no se realiza correctamente en el componente RUP Upload.

La gestión de los envíos se realiza correctamente, sin embargo en el caso de producirse un error en la subida de ficheros, el componente no es capaz de gestionarlo correctamente.

**Comment by oierjim** [comment]
Hola:
Nos estaba fallando en IE9 esta incidencia y como la necesitamos pues he revisado los cambios que habéis hecho para esta incidencia: el archivo jquery.iframe-transport.js 
Al copiarlo ya no daba el error de carácter no válido pero a la hora de pintar el error siempre pone success en vez del mensaje que entrega el servidor.
He repasado un poco y el mensaje ese lo pinta en la variable errorThrown en la funcion fail del  jquery.fileupload-ui.js y tirando para atrás esa variable se envía en el jquery-1.8.0.js error = statusText; y como en el transport el cambio vuestro modifica el statusText ahí he puesto la respuesta del servidor en vez de lo que devolvía ahora ya que con el UdaMultipartResolverla respuesta del servidor es la siguiente: <textarea status="413" statusText="">El documento es demasiado grande, por favor prueba con otro m?s peque?o. (10Mb)</textarea>
?No se si es lo más correcto¿
