### ISSUE TITLE
rup_autocomplete pierde el valor al entrar y salir del campo

### ISSUE THREAD

**Issue by bilopavi** [UDA-EJIE/udaRUP#8]
Al editar un registro de un **rup_table**, la función **populateForm** de **rup.utils-2.4.6.js** no inicializa  la variable **loadObjects** de los elementos rup_autocomplete y provoca que al entrar/salir del campo, éste se vacíe
Un saludo

**Comment by enekoza** [comment]
La modificación en el método setRupValue ha resuelto el problema.

Como indicabais, no se estaba inicializando correctamente el objeto loadObjects al asignarle un valor al componente mediante el uso de dicho método. Debido a esto el componente al perder el foco eliminaba el texto que existía en el campo.
