### ISSUE TITLE
Fallo en contextMenu - Itsm:WO0000000024148

### ISSUE THREAD

**Issue by hmartinez85** [UDA-EJIE/udaRUP#86]
No funciona el hover en el context-menu
En el rup-base.css existe el estilo para el selector:
.context-menu-item.hover {
  cursor: pointer;
  background-color: #bababa; }

**Comment by xaabi6** [comment]
El commit 775fdc6fb16acbda9cc2394b444080784d94f1eb corrigió esta issue.
