### ISSUE TITLE
rup_table filter

### ISSUE THREAD

**Issue by gorkazar7** [UDA-EJIE/udaRUP#9]
Buenas,

En el pluggin filter del table veo el botón limpiar. Me gustaría hacer algo despues de este boton. Y viendo el código veo lo siguiente

	jQuery.fn.rup_table("extend",{
		cleanFilterForm : function () {
			var $self = this, 
				settings = $self.data("settings");
			
			$self.rup_table("resetForm", settings.filter.$filterContainer);
			$self.triggerHandler("rupTable_filter_beforeClean");
			return $self;
		},

He intentado implementar la función beforeClean pero por lo visto no hace nada. A parte el nombre lo veo un poco raro ya que ya ha limpiado el formulario no? Entiendo que se debería llamar afterClean jeje

saludos

**Comment by gorkazar7** [comment]
He extendido el fichero con el siguiente código

(function ($) {
	jQuery.fn.rup_table("extend",{
		cleanFilterForm : function () {
			var $self = this, 
				settings = $self.data("settings");
			$self.rup_table("resetForm", settings.filter.$filterContainer);
			var bfc = $self.triggerHandler("rupTable_filter_beforeClean");
			if (bfc === false || bfc === 'stop') { return; }
			
			if ($.isFunction(settings.filter.beforeClean)) {
				bfc = settings.filter.beforeClean.call($self);
				if(bfc === undefined) { bfc = true; }
				if ( bfc === false ) { return; }
			}
			return $self;
		}
	});
})(jQuery);

**Comment by sergisu** [comment]
Hola,

Para capturar el evento tal como aparece en la versión 2.4.6:

`$("#table").on("rupTable_filter_beforeClean",function(){console.log("antes de limpiar");});`

Si se actualiza el commit UDA-EJIE/udaRUP@29560ce en los ficheros de RUP, el código para capturarlo es el siguiente:

`$("#table").on("rupTable_filter_beforeCleanFilterForm",function(){console.log("antes de limpiar");});`

UDA
