### ISSUE TITLE
[rup_table] ReloadGrid selecciona un registro o no (v3.3.0)

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#91]
Tenemos una tabla multiselección y al hacerle un "reloadGrid" siempre selecciona el primer registro. Hemos intentado deseleccionarlo en varios de los eventos que lanza la tabla al cargarse (jqGridAfterGridComplete, loadComplete...) pero estos se ejecutan siempre antes de que acabe el reload y este al final selecciona un registro.

También esta ocurriendo, por esta misma funcionalidad, que si ya tienes seleccionado el primer registro al hacer el reload, se carga deseleccionado, comportándose "diferente" dependiendo del estado de la tabla.

Como posible solución/mejora se nos ocurre añadir un parámetro al reloadGrid que indique que no queremos seleccionar el primer registro para así no cambiar el funcionamiento por defecto:

```
jQuery.fn.rup_table("extend", {
    reloadGrid: function (async, notSelectFirst) {
          var $self = this,
                settings = $self.data("settings"),
                page = $self.rup_table('getGridParam', 'page');
          var ajaxOptions = $self.jqGrid('getGridParam', 'ajaxGridOptions');
          var ajaxOptionsAsync = ajaxOptions.async;
          ajaxOptions.async = false;
          //  var ajaxOptions = $self.jqGrid("setGridParam", {ajaxGridOptions:ajaxOptions});
          $self.jqGrid('setGridParam', {
              ajaxGridOptions: ajaxOptions
          });
 		
          $self.jqGrid('setGridParam', {
              page: 1
          });
          $self.trigger('reloadGrid');
          ajaxOptions.async = true;
          $self.jqGrid('setGridParam', {
              ajaxGridOptions: ajaxOptions
          });
          if(!notSelectFirst){
              var nextPagePos = jQuery.proxy(jQuery.jgrid.getCurrPos, $self[0])();
              $self.jqGrid('setSelection', nextPagePos[1][0]);
          }
     }
 });

```
Se puede ver en la x21 en el ejemplo de tabla multiseleccion llamando al reloadGrid.
```
$("#table").rup_table("reloadGrid");
```

**Comment by xaabi6** [comment]
El commit 59158f9ac8a893e8cc7d983a5ab7e39063c29dd9 corrigió esta issue.
