### ISSUE TITLE
rup_date time

### ISSUE THREAD

**Issue by oierjim** [UDA-EJIE/udaRUP#93]
Hola:
Tenemos un rup_table con una columna que es un timestamp que esta definido con un datetimepicker. Cuando se abre el pop up de edición, va a través del setRupValue y el new Date() falla por el formato  de fecha de castellano, ya que no hace ningún parse date. Y al modificar el setRupValue, también hemos tenido problemas con el getRupValue cuando va por el if de datetimepicker  también falla. Nosotros lo hemos modificado en el rup_date en la versión de rup 3.

**Comment by hmartinez85** [comment]
Buenos días,
Podías poner un ejemplo, no he podido reproducirlo en nuestra aplicación.
Como lo has solucionado?
Muchas Gracias.

**Comment by oierjim** [comment]
Hola:
Por ejemplo: Si defino dos fechas con datepicker:
	
$.rup_date({
		from: "fechahoraInidetail_table",
		to: "fechahoraFin_detail_table",
		datetimepicker:true,
		showSecond:false,
		timeFormat: 'hh:mm',
		labelMaskId:"fecha-mask"
});

$("#fechahoraInidetail_table").rup_date("getRupValue");   // desaparecen las horas.


//La solución que hemos puesto en el getRupValue del rup_date

getRupValue: function getRupValue() {
		if ($(this).data('datepicker').settings.datetimepicker) {

				return $(this).rup_date('getDate')+":00";    //si es necesario los segundos, esta funcion no valdría para nuestro caso nos vale.
			} else {
				return $(this).rup_date('getDate');
			}
		}
//Como comentaba, en el popup de edicion que salta automaticamente y setea los valores ejecuta el setRupValue y este también falla por lo que lo hemos modificado. Añadiendo un dateFormat una propiedad nueva.

setRupValue: function setRupValue(param) {

			if ($(this).data('datepicker').settings.datetimepicker) {
				var fechaArray = param.split(' ');
				
				var tmpDate =$.datepicker.parseDate($.rup.i18n.base.rup_date.dateFormat, fechaArray[0]);
				var time = fechaArray[1];

		
				if (tmpDate.toString() === 'Invalid Date') {
					return '';
				}
				var timeArray = time.split(':');
				tmpDate.setHours(timeArray[0],timeArray[1],timeArray[2]);
				var dateObj = {
					hour: tmpDate.getHours(),
					minute: tmpDate.getMinutes(),
					second: tmpDate.getSeconds()
				};

				var formattedTime = $.timepicker._formatTime(dateObj, $(this).data('datepicker').settings.timeFormat);

				
				
				$(this).datepicker('setTime', tmpDate);

				$(this).val(fechaArray[0] + ' ' + formattedTime);
			} else {
				$(this).val(param);
			}
		}

Si hay otra solución mejor lo ponéis por aquí.
