### ISSUE TITLE
Checkboxes en Edición en formulario (v3.2.0)

### ISSUE THREAD

**Issue by Menengol** [UDA-EJIE/udaRUP#94]
Cuando navego por los registros desde la ventana modal en la edición de formulario se dan comportamientos extraños con los campos de tipo checkbox.
El resto de campos se actualizan correctamente pero con los checkbox, en el momento que paso por uno que no está marcado, a partir de ahí ninguno se muestra marcado, a pesar de que tengan el atributo checked informado.
También nos pasa cerrando y abriendo las ventanas modales.

El código del javascript rup.utils.js es este (línea 348 y siguientes):

```
   else if (formElem.is('input:radio') || formElem.is('input:checkbox')) {
	formElem.each(function () {
		if ($(this).val() == aData[i]) {
			$(this).attr('checked', 'checked');
		} else {
			$(this).removeAttr('checked');
		}
	});
   }
```

Proponemos que lo que se modifique sea la propiedad en vez del atributo, o las dos cosas, quedando así:

```
   else if (formElem.is('input:radio') || formElem.is('input:checkbox')) {
	formElem.each(function () {
		if ($(this).val() == aData[i]) {
			$(this).attr('checked', 'checked');
                        $(this).prop('checked', true);
		} else {
			$(this).removeAttr('checked');
                        $(this).prop('checked', false);
		}
	});
   }
```

Gracias y un saludo

**Comment by xaabi6** [comment]
Aupa, hemos probado tanto yo como mi compañero @hmartinez85 y no hemos conseguido reproducir el fallo del que hablas, ¿Podrías postear algunas capturas, por favor?

**Comment by Menengol** [comment]
Hola, claro, os pongo unas cuantas capturas.

Por ejemplo, el primer registro que abro lo marca bien (Inicio de oficio sí):
![image](https://user-images.githubusercontent.com/35994357/36718848-7fe0ad1c-1ba3-11e8-97d5-414fd1bb0e32.png)

Paso a la siguiente que tiene el Inicio de oficio a no y no lo marca, hasta aquí bien:
![image](https://user-images.githubusercontent.com/35994357/36718929-cc9763bc-1ba3-11e8-854e-443c376a71e2.png)

Vamos al siguiente registro que vuelve a tener Inicio de oficio a si pero esta vez ya no lo muestra marcado aunque si tiene el atributo checked (y a partir de aquí ya no saldrá marcado ninguno):
![image](https://user-images.githubusercontent.com/35994357/36719152-7f2b015a-1ba4-11e8-9568-74697d284172.png)

Por no distraer la atención con el tipo de checkbox, también nos pasa aunque el checkbox no esté estilizado.
![image](https://user-images.githubusercontent.com/35994357/36719760-4d95fc2e-1ba6-11e8-9081-c312a5832ef3.png)

Nuestra solución actual pasa por capturar el evento que lanza cuando rellena el formulario:
```
       // Marcar checkbox del dialogo
       $("#family").on("rupTable_afterFormFillDataServerSide", function(){
         if ($("#allowadminstart_detail_table").attr("checked")){
           $("#allowadminstart_detail_table").prop("checked", true);
         }
       });
```

**Comment by xaabi6** [comment]
En la versión 3.3.0 no hemos podido reproducirlo. Prueba con la [aplicación que tenemos en producción](http://www.ejie.eus/x21aAppWar) a ver si te sucede y nos cuentas.

**Comment by Menengol** [comment]
Ya, ya probé en vuestra aplicación y va bien.

Estuve mirando a ver si tenía alguna configuración distinta o cargaba algo de forma diferente pero no conseguí ver nada.

En fin, seguramente probemos a migrar a la versión 3.3.0 y si no con la solución que usamos nos vale.

Gracias y un saludo

**Comment by xaabi6** [comment]
Por favor, vuelve a comparar los cambios del componente entre las versiones **3.2.0** y **3.3.0** y si no encuentras nada relacionado con el fallo, será mejor que os actualicéis a esta última versión. De esta manera, evitareis futuros problemas a la hora de actualizar UDA derivados del uso de soluciones propias.

Dicho esto doy por cerrada la issue.

Un saludo

**Comment by Menengol** [comment]
Con la versión 3.3.0 funciona bien.

Gracias y un saludo
