### ISSUE TITLE
[rup_table-responsive] Columnas descolocadas con mas de una tabla (v3.3.0)

### ISSUE THREAD

**Issue by GardiHuts** [UDA-EJIE/udaRUP#98]
Estamos teniendo problemas al usar el plugin responsive del rup_table cuando tenemos mas de una tabla en la pantalla. Las columnas de una de las tablas se descolocan con sus respectivas cabeceras. Nos pasa tanto en un mantenimiento Maestro-Detalle como en en tablas independientes entre ellas (una tabla en la pantalla principal y otra en una modal por ejemplo).

Se puede ver el error en la x21, en el ejemplo de un maestro-detalle:
http://www.ejie.eus/x21aAppWar/table/masterDetail

![image](https://user-images.githubusercontent.com/11626735/37284397-b17a0ab4-25fb-11e8-9b40-1e587675add4.png)

**Comment by Menengol** [comment]
Nosotros también tenemos este problema. 
No me había dado cuenta de que es por el plugin responsive.
Tak!

**Comment by pruizmig** [comment]
Una solución provisional es dejar de utilizar el plugin "search", en cuyo caso si se ajustan bien las cabeceras y las columnas. 
El problema parece producirse cuando en la tabla hay una fila entre la columna de titulos y la primera de datos (el plugin de search, si la tabla tiene agrupación, etc)

**Comment by GardiHuts** [comment]
Pues parece que no es solo por eso que comentas @pruizmig, no usamos el plugin "search" en ninguna tabla y he desactivado la agrupación para probar y nos sigue ocurriendo :( :

Tanto en tablas Maestro-Detalle:
![image](https://user-images.githubusercontent.com/11626735/37762304-301c0e90-2dbc-11e8-9ed9-879a15cb5a34.png)

Como en tablas independientes pero teniendo varias en la pantalla:
![image](https://user-images.githubusercontent.com/11626735/37761970-6c92b5d2-2dbb-11e8-9ee1-1b34902d68c2.png)

Gracias de todas formas.

**Comment by pruizmig** [comment]
Mirando más en detalle he visto que parte del problema viene por el colspan de la fila intermedia (del search o del agrupamiento) ya que es mayor que el número de columnas visibles de la tabla (parece que no tiene en cuenta las columnas marcadas como hidden)

Por ejemplo en nuestras pantallas de mantenimientos ocultamos siempre la columna "id" por lo que el colspan es uno más que las columnas que realmente se muestran. Ajustando por jquery el valor del colspan se alinean correctamente las columnas.

A modo de ejemplo, en la demo de UDA (http://www.ejie.eus/x21aAppWar/table/masterDetail) lanzando este jquery se arregla la alineación (originalmente tiene un 7 en colspan)

$("#comarca_search_searchForm th[colspan]").attr("colspan", 6);

Espero que sirva de ayuda.

**Comment by oierjim** [comment]
Hola:
A nosotros nos sigue fallando, como puso @GardiHuts en su último pantallazo esto pasa también en las tablas que no tienen el "search". Donde encima no aparece nada de colspan.

Saludos

**Comment by GardiHuts** [comment]
Si, hemos migrado a la 3.4.0 para solucionar estos problemas y también nos sigue ocurriendo lo mismo, es mas, en tablas con agrupación, los headers de las columnas se colocan mas o menos bien pero el contenido de las agrupaciones nada de nada. Y se nos descolocan las columnas de otras tablas ya cargadas.

![image](https://user-images.githubusercontent.com/11626735/40536258-d41e91da-600b-11e8-8a15-ee7e814007e6.png)

@xaabi6 Podríais reabrir la incidencia? Gracias.

**Comment by oierjim** [comment]
Hola @GardiHuts
He visto que para las columnas tenemos unos width, y aparercen, pero los th se crean con otros width. Si reordeno la tabla pinchando en la primera columna se reordenan y se ve bien con los th los width que se le definen desde el js.

También nos pasa cuando no hay registros que la fila de no hay registros no llega hasta el final.

**Comment by oierjim** [comment]
Hola @GardiHuts @xaabi6
Siento ser tan pesado pero he encontrado una pista.

Mi caso es que en una pantalla tengo dos tablas, la de arriba 3 columnas y la de abajo 10.
He puesto un break point en la funcion reDefineColWidth() del rup.js, y al pararse para la primera tabla (quitando los elementos que no me dejaban ver la pantalla) veo, la tabla correctamente, calcula los widths de las columnas y todo correcto. El problema es que vuelve a pararse otra vez en el mismo método, para la misma tabla, pero esta vez carga la información de la segunda tabla. Cuando acaba hace lo mismo para la segunda pero esta vez como la ultima tabla es ella mismo pues esta se ve bien.

Espero haberlo explicado bien. Básicamente que no esta teniendo encuentra nuestras col widths porque las calcula mal cuando hay mas de una tabla en la misma pantalla.

**Comment by oierjim** [comment]
Para el que tenga el mismo problema,
He modificado la siguiente función en el rup.js

```
function reDefineColWidth() {
 var $self = this;
 var widthsArr = $self[0].p.colModel.map(function (i, elem) {
          return i.width;
      });
 for (var j = 0; j < widthsArr.length; j++) {
	 $($($self.selector+"_div table th")[j]).css('width',widthsArr[j]); // LA LINEA DEL CAMBIO
	 $self.find('tr').find('td:eq(' + j + ')').each(function () {
		 $(this).css('width', widthsArr[j]);
		 });
    }
 }
```
	
Cambiaba los anchos de todas las cabeceras de todas las tablas, por lo que si se daba el caso de varias tablas con diferente numero de elementos en las cabecera una se vería mal seguro.
