### ISSUE TITLE
Tooltips de los registros de las tablas de los mantenimientos (v3.2.0)

### ISSUE THREAD

**Issue by Menengol** [UDA-EJIE/udaRUP#99]
Para conseguir que aparezcan los tooltips de los registros de las tablas de los mantenimientos hay que buscar un punto sobre el registro que es bastante difícil de encontrar y además desaparece muy rápido a pesar de no tocar el ratón.

**Comment by GardiHuts** [comment]
A nosotros, en la versión 3.3.0, nos esta pasando exactamente los mismo. Es difícil conseguir que aparezcan, no es en cualquier punto de la celda, y ademas desaparecen al momento.
